### ISSUE TITLE
Machines still utilize energy when at current maximum storage

### ISSUE THREAD

**Issue by jepstein30** [sparticle999/SpaceCompany#101]
Again, not sure if intended (and maybe resolved with the machines tab?) but machines still utilize energy despite not producing anything due to being maxed out on storage. 

I think the machines tab will have the option to toggle machines on/off but I think a feature where machines don't consume energy when not producing anything is still very beneficial.. having to toggle machines on/off every time a max is met would be more click-intensive.

**Comment by adamzam** [comment]
some machines, like charcoal, are used by other things and because of that they're still doing something.

**Comment by jepstein30** [comment]
for those machines, it would make sense to work in the same way as well. Basically, if there is storage space, the machine should 'turn on' and consume energy to fill up the storage. If no space is available, it shouldn't consume energy. 

for machines like charcoal, it would constantly be getting turned on and off but shouldn't also be consuming energy all the time (especially if your production >> consumption rates). It's really a gameplay issue that is up to the developer to decide how to approach but I think it would be a much appreciated modification!

**Comment by IanGolsby** [comment]
The reason I wouldn't want that to be put in place is think of this. Three of your machines are at max storage. Together, they use up 8000 energy/sec. Now, you're being told you make 13k/sec, when you only really have 5k to spare. So you need to upgrade silicon production, and but some t4 silicon producers. You spend 13k energy/sec. You're still in positive energy which is great. Then you spend some resources, or upgrade srotages, and suddenly you're losing 8k/sec energy. As a player who always tries to stay in the positives, this would be devastating as I can never tell how much spare energy I produce.

**Comment by jepstein30** [comment]
That's a good point but a simple solution would be to show "maximum energy consumption/production" in the energy tab or something along those lines.

It seems like a future feature of the machines tab includes being able to individually turn machines on/off. With that feature, you can turn machines off when you are at max capacity... but I don't see why that level of micromanaging is necessary thematically. If machines aren't producing anything because the storage is full, they shouldn't be consuming energy.

**Comment by DMwdm** [comment]
i would absolutely require the tech to shut down energy consumption when inventory is full !!!
thats why the accumulators comes real handy at if it goes negative for a little time
