### ISSUE TITLE
energy crisis

### ISSUE THREAD

**Issue by fuzzybear7** [sparticle999/SpaceCompany#107]
the energy keeps going to zero whenever I switch tabs.

**Comment by sparticle999** [comment]
Do you have a video/screenshots/gamesave I can use/see?

**Comment by adamzam** [comment]
simple solution, keep it as a seperate window and put it in the background. the same thing happened to me, i fixed it like this.

**Comment by Craiel** [comment]
This should be fixed now as of 0.4.4.4 Beta
