### ISSUE TITLE
Stargate Activation bug

### ISSUE THREAD

**Issue by lcodeca** [sparticle999/SpaceCompany#132]
I clicked on the activation button of the Stargate Room and even if the resources were XXX it activated.

<img width="789" alt="screen shot 2017-07-06 at 15 10 52" src="https://user-images.githubusercontent.com/5700703/27912553-a87a2398-625d-11e7-860d-44506506afea.png">

<img width="234" alt="screen shot 2017-07-06 at 15 10 59" src="https://user-images.githubusercontent.com/5700703/27912560-ad53310c-625d-11e7-88fe-eac9046af1ec.png">

I just hope that when the Stargate Tab will be implemented, my tab will be resected or, at least, I'll be able to use it.

**Comment by sparticle999** [comment]
oh. That is not meant to have been released. I removed the costs for testing and didn't put them back.

**Comment by sparticle999** [comment]
All fixed now. Thanks for reporting!
