### ISSUE TITLE
Infinite meteorite glitch

### ISSUE THREAD

**Issue by iuriguilherme** [sparticle999/SpaceCompany#138]
The "Converting Max" mode is converting the amount of *Plasma* that was present at the page load, and not the actual amount of *Plasma* available.

Finally I got **500k** *Meteorite*. Lamed up the next two days though.

**Comment by sparticle999** [comment]
This is fixed now.

**Comment by iuriguilherme** [comment]
Now the available *Plasma* displayed in the **meteoriteEmcVal span** of the **EmcPage tr** is following the available *Energy* level.

**Comment by sparticle999** [comment]
Ok

**Comment by sparticle999** [comment]
Thanks for reporting these

**Comment by sparticle999** [comment]
Fixed
