### ISSUE TITLE
Research Energy Efficiency allows purchase after #50

### ISSUE THREAD

**Issue by sudokuninja** [sparticle999/SpaceCompany#144]
I maxed out the Research Energy Efficiency (after the most recent update to v0.4.4.2 Beta) to 50 of them, but clicking the "Upgrade Efficiency" button still costs me resources.

**Comment by sparticle999** [comment]
and did your efficiency increase by 1 or stay at 50?

**Comment by Craiel** [comment]
are you sure you are talking about the correct efficiency research? Energy Efficiency is the only one that is capped at 50 (i.e 50% reduction). Both Research Efficiency and Resource Efficiency are "infinite"

**Comment by sudokuninja** [comment]
It stayed at 50. Essentially I wasted a few resources on making sure it was
in fact a bug.

**Comment by sudokuninja** [comment]
@Craiel Yes.  It says 50/50 but when I click "upgrade" it discounts the resources for the 51st, etc. but does not increase the number of efficiencies.

**Comment by Craiel** [comment]
I submitted a fix for this, the text will now change and the purchase button disappear once the maximum has been acquired.

**Comment by sudokuninja** [comment]
It works great now, thanks!
