### ISSUE TITLE
Converting max plasma → meteorite costs no plasma

### ISSUE THREAD

**Issue by quyxkh** [sparticle999/SpaceCompany#146]
I doubt this'll be hard to find, but here's the save just in case.  Set the conversion limit to max, convert plasma, you get ~66k meteorite and still have ~200k plasma.

N4IgbgpgTgzglgewHYDkCuBbARtEAuEABgDoAWM4gRhABoQAbAQxgBcAxOADwgBMBVAA49GLCPkqkAnJNKkAzACYArJMoA2SXQFMYGRvgWEl6ucSUAOAOyWV5taTV0ACgGU++Us7cu49SFABhBFZxSgVLOSVLLz4AcQR6HiCQvEowiKiYvihGJDhMZJZ8cyNlJRiAFQV8QkqFHz9oQvxJOUJ29rr4xOa8Vo7OkFc+Kuzc/IxetRKBugALCBFcVPnF0SgXAUYAYwgAWQgWRnpe82VBhaWoWIhJ4KK8S1IZ1auGuG3kKakLtegKhAAc0B9F4+BYUDQEC0Oj0LA+4hhzDhH02O32h2Op1UHSRuhEqN8Hy+93wlkkhkG2mRBO2B1ECCgcFEvUohDU0RA1Px8O2AOBoJ44Mh0JAECQ0EBAE98JEbEpyGFpOZSApKOZ1HQsCJ1jLUrUQNqWLr6VjSakFJJppyjbqbncUkrrVqddApWjdqaTubrBqFC7jW6quIba6oFKql7euFyZILAHdVV7dHrNJ44awxH6ltPZjvY61BzJDYE0G5DVS+GKnIo+alEoBgbbWXk3WG7MM4Gq3IPRijvmHnI2h3tnNGFBPscAKJIQFwCX4Bt0Ufjyf0GdziW1lIWDTLscThDT2fziCtlKWuSeEArw/HzcQADyaBYAhfHjoMAS46cuQg9HEQhNBAL8mCgX8JXobcHmLZ51U/b9wL/ehzweNI5EsBRzHMBCwIg/9n1fd88DkOgMEOMcJRcI54WQMkcJAciWEoiBqIJZBe2g8Q7DVBimJYtjaKQCpmXGApzUoJQFDkNQDSQNBtlBcdBMQJBFwY+TFMWDYaNUzi816BtFBsa9NKUnT2OE0S8nEi9jDUDDOT0QEUW2RdykYxgXNpfT+16UhMPsSw+K81zUMXDlKGsa9nNchp/F6DCNXVf0QAAMzQeBkAAJUWbYWEZRdgIyrKkFynYCo2HM+zNFJzDaUhCFkOgStU8r8sZESjhsh0HnrGTCEtFrMravLKveT4kH8yTDAUVKEF8Aw1DVWRBgW+hqMZLyxDwBRlokRqDXWlAIE4FhNpyQEdqk1VsKpTABHwNRKC0B6uN29o41ejABHCvBC0kBi3x+gArHYAGtAO+gQwe2cH3vsIGHth8G/rmg1gZhiHH18Vkhq5ZHsZfN80KO3wOH/IV9TodaKcSXzaoeZaFGvWm4EprqxN6sl2lIkA2cpiaSUdQg0g89bsrgQEP353xJcBBmBwMFVCD5iWpc5nro1IFRHFl+h5fpCBGWZCBWTSVKmOODwwjOAHiAanXAZexi8wu7aDCAywZsGK36BOs73aum2ZAa33TygQCDQwCP3soJL2TIiOAHUEAQJJzWmSRVdeMApQAESZegALwYxc4LouoIM81DELA1LjzwvfBQ25emizkG4r5ucaV/6db1zum+LwiSfEPW50BRgh5LpcQAnqfK8VxKsI0a95+nv65GkW26HXxeiUm/yNTaVKAEc0FyFhMGnp66HPy/r8X6r3uMDCPPvpAr4wDeEgzlIhx3iAD+X9p5GxNiyCSKg163EAs8KIskDRXQwEHHabI4GWAQbvW4AdzqVQ9h9YsPtEG3D2BHMk48SGx2rheICdgsEYFIRKa4rcJJb2znQRgPAwC5F2DwG+pcDScO4UgXhoDqFoUanQkAQieG8A3iwi8V5gocK4bIvhlce5tyanzGRIi5EaOJsRBiPA4CMAwMgdRzdxAeRMWYix08l4SVVINOgtjzFIEscXTeV4oquNMe4zxG0D7CzQlYYsy5xxYClBKfhbIIlQCiTEp+6IX6yGmPExJEB5Hc0eLzF22xInRKyZXMBTIIE0KePuVcR4S57RWodKpd4Np4ODrtfaq0DS3jXDglBi4WZYReDeA8a5+QgjBHgCEUI6AAHc048CwGgKATDEQgFmenBZSzoBxxdms+ZiymGp3ToZYaSz0RjxOUgFJ4jZQcgueiQ5f9Ql8wyqc3YmjzROzubsB5ABJJAo8LRfKfIYh4DFwa+DUo8Og4L6BIEcSkaYhhoUQr+mEQgZxkWwqFlNH0jUPJpXDMsfFhKqpXL8jXBUDgWokoADKMG4dGUWcgXYEqlFsw4xsylm3NNnHZczYHmHgYMXZvT9ToMwasuZPSWk7UMIQqSwq5nbBfOsYoDFdnKq7O9eQ2dgIapVdAB50ZKBxmvDoJoBrI4CLoOawIlqX52GAragIlrUVGDUB5Z1lr3kpAcF9BgzALVdhHsRMIriIBpUZBAVgyw2jhsjVAaN6x4V9Wks8eNUaY1QE1hMfy3t44ZsTVm7F/kZLSToPOEqyw4kgErZlaAKabZSGAnWmA0AfWgqAizCtSAq1QFKabPGlgDQwG2OzPRY82RhHjsQbCPioqciYFgKONrGBYCNaw4KicA1YDRuyYdTq13vXCEoZ6qUl3BkeGatdVQN07mCvHa9WAkwKIeNJMISg+YXoUNs09e0GIXvLP9ADN65B3qZntIVq7n1yE3vus90HqzbKAqe+CO6KikFlAaC9pBwOAXsKQeOnqb2kD+vYP9i6SNx2ehYCQesoAIDhocCsIAGNMfYFCEu6hyRSAUFQWQTwNTDuvGx8Ghw2CcdGYKYUUyhm3A+McJwTBP4GH3PJgp9AlOXzjmqTpCwY4aa05/P62dOSjnU4p5TLAO1PSMDTTgcATEwEsouezjm4DOaEnHVoe03NOcsqioctz+YOf80JGz+o4wuxgM/PMysArSTaA7YwwVgp6xi2S44oq0GCowYMDLuZ+zSq2q0uV3sFXRwon+J6/UJX8T/KKj1n66tVYlMVy6qDmWEEwoMeE3UJjK2zmE8ws69oyUksBPrXNRU3QGb16yEx2v4Jy0KxBv9rHKGeIoWdw7RYNjVLvX+oq6kHUGICX+S3WmzbuiO3w/glr1Py3dhtMqHundu40KAl3rr9Ju5+YJkKSiyG3rOjQEgfPXngPQYkcLXttMex9mH32+m3UGeY5AqcoBiatSUMiackCY+x26/pvt8f8KRYxMnJTrn/Uwk5Knzc/qNRknj5A08It7XYZT5AABFC+UBwweGjvjvn45wyNpIstbrMURf8/DGjOpVpWdIFFwL90APWQWEapyakEoWBTk4AU7hlUDAu114cA3RuRCdQW7ZQcQ5RZm+Uxbw39LrdQB+bsFMcgSjAXN/r13xvGQDvKYOXbdBuHKswB4Dyke0CYAlzJZq4Adjx4wJvAjHkYAKSEpbt3Jv/qfhz6pPPQfSWFcZiGTk2f8ol8D+71FhHq/F+QKX93EW2TLU/NVII0zb4gR7wgaZEvVRlwH+iXvOa7ceGCnzAr3Lh8a8zrqiP4o32r8/hL5aFIDSQE/gACX/Lmus1pd9r5D9y313s6CnW0FGq1V4b+cDv4m5hOSygBW75l+gsSv8V5/8kv/tGBTvPl6NkqcLjuPv/uzrjBJGyBjGvgvFYqkHrAIIgQ4rFuSgivIPjGgZ/EgV4q+ouEYMnngUcA4kvnZBEC7FNkgLEnzLQRgd/sak8K0HQIwZXN0I8i0IoGkOwdZGIgyFyoytfiADwAxo5qbq4hITwBLhIJAeIQtDwPSCxIlMOuGqwAxmylai7DwEmloQ2pgZXqXLPHoZoQgNoaih6gaGYRCBYe2rAY6PAeGiIHMGxFateHoa4e4RLizNhMBF4cxD4c9oEBJNMBhC4UEUcBsJQWhJSB5BVBfAXjovlEkYyBLslKoBwqke7oftDtPh9OYErtIjkZVBfm3IDJ+J8MRL5iBNUedEYb3GkFkXUQgC+FPu/j7n/hAHSm2jod0b0YYcweaD7lntVIMW/r0NICOuMYGlAB3ooE2NAMxPoFCoaMsWOInrGMBDgFACsR0YlAqIWFqBsYwCWjXBIJEBEkgEgHRIXjeLkLcXCo0Zrt1ioNcU8R3oWFFKlAUjccgOUTygdoaPQEPpVKOFhlqKCdMuCW4S8TXM9DaNCbCQcXWOWq0ROAsFaiOp8JiUMUAXWPlrieZpMRJJSFUYyCSV8YMI8XAHML4O7gYKlLSfSUwONPCReLIBTiyQyZVGRjYPYBwjcXSbyekSEayHGCzmIdGssa5tKX0Q0cMf/HNDWmYcsecReIKtumqXsYCdgSJjKauHMHwEgKCUxlTJMqKEWtpOZlTAANogBoCmmMbgy9J0BOlmngwABCzAHwM4koMo7pzpcMPctAjpwZrpiEYZHpLpewOw9JEoMA0ZAggIOQehuUX4iyuwFQEAEJQZnpLgiELgUoMaGA0ZEZdKz61Q+ZLplZ1Y5Znp+c+hLeak7pKZaZEAG4p4OZeZjp7ZnCrEiEPZcwDZLp2ULp4mkm1Z4ZnpPpXY7MSZNZcMWm+Io5y5sIjAIk0A05MZcMc56wC5wYS54MU4GAbkx5F+a58MHK4CEAW5UA1AF5N5XK95O5EZ+cJZdEx5H5X4zxWJYgx5dZmGx5wwV5wwwYAAuhwtwgyVgKCPgA6bua6a9seT6fANsP6VANKFeaGceYWWBFeXGaOKeIuX2amQOV2RKMOcmeRXofheONRXhUWSWaIGWW2bRRABmW0ROHebmSOd+c2bXl+TObWTem+Z6eOexhJv+EeSJXDHWeWKhWGAuVefudAIeeJaJc+sBXJeDCuXoGBRua+VeaeeebpZeU+UIabPeY+eZc+dZezFAJpXDD+cJUha5X+dAABbpaBSBW4LJUhWpUyNGvWVBSAEcFgDACaZ6eMg6daUaRUGumGaBMpCxbcIlcujMhYv8ElT2usDGsXAxUlWFUWtxbsFFRGbFWKEwtKCgPSmGV0jUnVWAGGcdPVcuAkEwAIG2n8kwkZsxt0V6M1WGfVhKE4EPrgGRK1hAMNfwf1pgLNSBADotedokItVDv4ItaJpOTJdOc2MFaReKAGSgl6QgJwGGQIImmOm0TAKnB4tAItbMvdVAGwKCYyJQItYslzItWZNpONdMpNdVZKIcB8HdXoV9u1QGtwotbFLSP9YDZ8IVd1cCusP1UUMNKVPDZHPMFKIoVdKgJDQsPkRgItR8DNZDaIKOGDQ9ZDaBAEGvoDXTQzdmggAIBlRdRuYtdyHoMZZWBpWGbcNsL+MHFNVZaIDDfZaIFOHsAECNZLXeY5bZUxJyg5duXLWLRANTRDS1a4p+UgMLd5TwHrZsP+Q1QgBgBgE6QpkJFrVtROSwLbZDZfHAHCOsI7TrTeObZbXkAUjbdldrWGdtQ7f7Ytc7a7YaiHZDdzWcTKiacyKRdHSdWdRzTSCgnHSwDALJU9eDa9WnE5YtZ8BbVbb7apO7YHfbWXUKfCOHVAJXVyIyP2OOebcNWFbcadVAODQhUDVhVKC3XQEHXSk6baTJqKJTcaZVRaSKKLSraINFROZPbJgssaMgDAPvo5noZCg6bfqCYmnsPjgLc/jvRAAAGriiZQH0v77DjiHWH1RoACCWaShXp/46NYot9iaWtKkwll1uZiAmUTgDGqZ0aCdV1f9t1/tXpKqwlFUcAxuEAADv9N1WtAtNVINQtgDRah1qDvIWtkDy9rZJR8IcDmFV0OD/tF9R9AAUmgAIKbNjW/ZfS4CIPshQ1Gkpi+AgGGWPQA0CJg1w3xbg1AwQzA3A8Ocg0/pfQANJoBwBoFQDP30Cv3b1Rr4X02fyA3xWYn6X6D92GmYmmWB16OjgeXq0z3wMYPAOmO3mCP4NhkiNLAX7iOsYQALK+AZwW3gPPWGOuOJCSVibB1eNhXKOJr2nc4EN77n1kTX12OP2OYKOv3Z0vYuZ0Agw0N0PJXMNLIc0cNhngwyNyPxPJUJBqOqphVfU9TqQWAqCmDtACZ+qpTlMTCNa1aDCNMLWnS4IladZsg9aCK15wOhM/3XWRPd2kMIjsF8VWNcpm0ePl3sYgBhWpnzid3UxzxMjPWok7jqichLPPVyGqyVJrPLPQBcGGTbPLhoBYAIh4CdKXMfBjBazmiQHKpXPbD7O4g3h3PbAd4djihMgkmyg35ID/NYlyHkjpLVUgv/C245JtDPR8x/MfCguxHKzYSpRXVShaT9HOPbCYugjl41RNGDSEYGgYtYsqF/hnPh44t4vsoa1TEFpQ2rFNYDTYZu7NPNaDBMDQ0dPZZda9PLiQhjpwU7SqiCsKRwAiu+EmokHivCugibz1RXgeQdM5AdTYuqsVTpEcloQKiDCavqubNoSLEGgGvjQov/QSqqtoArMqtnSQjg1yFpAfpP6TLg1GstBRTSCusOsNoWvLS+6r70A0NXyMkkRBshtpEEvvRbyFhdHgD/iRsN6/ysjPRGAuyQDBsCChtlHy1TGVEgBzC42APig1acv1zFtAjigcuss4143ijI6pD8vkme3Fy5kF41qI2gjqtyH1hd6tvduVQesWjA5ROAh64sbOR677No5eR67DtWi+xzuHCnOZxWv03FwtA34btBKfanDWCSTbv/goQptPPsiEZHvFwalMzopXGFvHNIAbLSx4DXgJkb1Pu+HGBnAeRvvihPsUsSgSnPRFHzAPv/t5sSSqzARE0DZNs9MtswcJ5w7xzwe/DE2NsnYdLSHICoI2EMZUQ6um6pbYdUQWuSR/rsG5DY4sbdTY5yF7S9ZUfQvzU5Jsgtu0d+vQ6HxPMNKe0/SYOFQvsdX8fAPatKkwRzTxuF0/0wBfjZowvfDpDCcydyfXuLgpTAQwDgoW3LCpRacu3kTRs05tCCqzz6c6fycseMqtBxogTaeGd6kwTMoVq7Ahi8EajkCc5YToqf61q7DHbtK8dk2NvXaDJk1OAfCQyrPheRcj7PQQsxdwx/TtjvF+fFLIEGhk1MEEmKLZyZe7DTzDtqgttZf7xcchLiCLsGgEoQAQAABeRK1KtXDXRnWBoSKo+MNX9XzHXMrIoxOc6Uia3XMR5XOKThApTkL1Q3DXqmjEU3zXmtcy/kVTXOGA833XeRx+BYMg0c63DXjn3Eh7rsGtT0lohgxA4QgMzaFIJq09t52WxLvs8tGHTUaO8tUm4ylpWg6zqqpc3384yahHKBbIY+l1APnHMOpwpQHkANy6NzMyLjEuO3HzsPDzW3DwPwKPiPFrxgHYRtv5LQqU+PyAw76oCoxYNhetq7CK6oigfMxPcKZH0khYvnDPB3/0tPutv5nul+TMtP6JMWpt8PIE0y44ZZwv6zz7Ls8Z7MkA5En8SZeAoA/gpUMsa+B1+AoA8ZAA+oQICyUXMNr9QOGwb9r9UCbzr0BsyaONr5hhbzb0oLNzr2oE7zb5YPrzr+YK74b5IB7zb2yN70b8b9b4b2EIH/HOH3byH0b477tNkaHy73H6b1FCsjr+qKn/7770nzr4YBn4b2qHn2b+b9Lzb9JIX+ECxpb3rysKb8ypXzb4oPX4b1eIH5EIXzJO317zX5b1nyX4b41E37b8b30/38X/H7b0Bn37b3byP7b7H7Pw4IXwFIP88Cv1n7Pw2IP1JFv0BhvzP+P6elv137P8tIP4WIP8Ohf/v6b8FIP2cHf4n7PxSIH60IXzIOIAAL4f+fi6SsAfCK/K9oAqvGvurxUpK9PI8kY4FxSzLRpNe4ADwMnm4QIDSA3/cKo5UfDTIJQPAY3srywx6wkBJEdkKgPhDtpMBvAc3rgJHYR5ViYQFAfwVIFYCgMlAvmAQLkDED0BZAngHb0oH1RqBxQNgfQPmKcDY+lAjNjQPYEMDeAifSgb5wIEBRiBa6CqjFSpjMDUBpVGAUoPnpwCWqgKFPOIAUDEC+KGZG0gsBUHwDdBBAsIKgOpDlUDcl9MwToOvByDUBiTWAJA18APBKBqUAgQYKyrPUYAd9fpksAcGzcfBqAttLJ1UgiRyI2g2ULTzIDlZDoAwesHwJIjxCAokkJIR0HrDsDyIWmNlCELSH1QEhmQxsEYFjyrFmUxQjIXq0bA5CWojIGuvgBAhzAG6dVGIVqF/gzg100mPAGlGOBtp/sehbUKERE6ydPuU9EALcXhBpRraqkGAN0JFYL1RQk8ecHgwKhIBV669Utn0IGGj19MO0MQuOHBj0BAy0iDhkw0gB/J1g3CEuAgg6Bf9dGmZHigAPMEeQrUoAI6j3TgGQoDQaAfAP0PoBtprBG5H4Sxn+G7CgREAVAW03F6gBfh7pAEXsNQHctVi8I8EUiKhGoD1oYI4XhCMBHAjRa1scAQiMdIj1UBSCXEX8PJGNI1wVIxEZCMJGSp049IskRMhFDhCAcrI/EciMGpxYSRGIxkdCNFosRuRmIpkbQVg7oi8R4o4UXPHWwCiZRQozkZ9jFHKi62JbSFNKOpHqjC2R+aPIqJ1EEi5RZNNUcaNQHK1byZo3kXUXHSudDRDI80Y8MNAyNEg84QEK8J0Euw4AcAr4dKAqDD8gWAZS9KaxqoRhd+QYnuhhhYx+iIw8/SMf6Mf54geagYrkEZXN5/CcgPUAMeCKzETAQx7pPMZgHrJ4iixGAaMcL1RE5jKxbuAsUyxLFstuEFYsmPQGrEti6x60BsTTF8DNiiRrY1MX7DrGDiIxx3Y4L2LnjpVUxSCOsdOJHHTjr+jVMcamMXGtiMxtImpF2KGTVIxx1/XZG2Kyrpw6xe4kcXuOv5Q4Yc+4paqNzrHnjJom428STzPGNFLxoBPMDeOfEjjXx/YccaNTvIDjpqQ4gCSON/HjjJRxY1MWBPLFri0BLHTcZBPHGrUeAl4xCTON/ibiUJZ4kIi+KwnQSNq/wT8VhOv5Ft62wkVMcRM1F1jyJVbYSCOKon41xxiHcsWRP1FQSWMjEzcexOv5k1Lx3E6CdxJHHcTr+lol8v+I1o3ix04obMqmNHR2i7yuEiSXok3FB1pK/YljMpKnI1BnRY9WITXx9HgDWAXTQQBxW0YsYDJHWIyR2TR4GiR0sdfsnoTpQECbJhkuyU+EWjC8zJ20CyQOS9CmTbJHFe0L5OckcUAgwyGpIFPMkuSHk4UzyS5OxTRSroXkuio0XikQBEpfYUUe5L8kdkOiKUtKVwVymxSQiBUjivvkrb41ipHZTbtZJ/5BSOyPPCqd5PlrgiIyaFP0mGOameke4PDcqvAFnAdSXS9FbEseWgE8UiKCZWAXiPfKCUhI/UuGINOLKllZp4MOstBKQp0o2aI4wKpmEvFbSuwWYJaUFXDFLTtGO0iMidNWkRkDGk0z0hflOk3T3uF0+6WJM2nvljaovKAOLz+GvTfyJtLyuCJckjTsykzPES5Moq8UISIMjioNOorC8I0swhSbi2MFGlFwCLMMVODSjwy7RUoJGZiVMkIzOyGMj4FjJxkQyDB4Qw4PCFnCeigBqkFZKAImnABnR4PWAKIEKofCE2sAWmTXz0DEVEyvok8AuHAHVEVM7krkQIg7DCTTYUcC4GVJ2HnAHhHCaAJwyFltERZH2e7B9A7CmjCBHYSkbtHbDtBwh9JSmHAOFkPBq8yUkiEUSeAMEYW6kBwEdz9geArAXrZ0awGib6ToiOAqYWYkOF316AAgMcAAAISmiyH0X4ndkToX2DsJEHrkV6UBwh0RCgT7JiEEAfSpyDugAHIYAQc9wmGSczdR7RSgYgMUX9yK9CAic8cEwJTmHCpw3VXwMgCDlTgmQwgPIPnI8yFzcOZgVKGXNm4kCdClcqANwJrnNDEqaAEOSDXbmRz7RaQWdH7mdwZ05S/cz/j/3HAiCR5BAWINDhlJByOQOlAubInEDkANQscw4PHMEEeBB50gjeSAC3kLkIAQcqwC7wjmdzrEDsa8L3KE5oDlgdAkCNEXd4kjfZzQu+TvPqjTkD5Uc9QMQHRSnzF5NfZeS+0Hld94RQCggD4CZAjMIF9okbOmE/kGgEFvgv+eOCz4oLU5t8hjObSwAtyroQc9QOnxfmHzUgxcwVLAvLkXzUgg8gPoArIX5wpwKAIOYNHrAABaAKO0CnmvyUCF3VhTR0cqXyv+H/IAA

**Comment by Craiel** [comment]
i submitted some changes to the plasma conversion just now, can you re-check and verify that this is fixed?

**Comment by quyxkh** [comment]
Damn. I was just coming back to abashedy retract my report. All fine now, thanks.
