### ISSUE TITLE
Extremely fast resource production

### ISSUE THREAD

**Issue by sudokuninja** [sparticle999/SpaceCompany#147]
I'm not sure if this is a bug with being offline for a long period of time, but yesterday I built my Dyson Sphere and for a good 15-20 minutes, all of my resources were being produced at x1,000,000 their normal production rate.  This was the first that I had played actively in a few days.  

This bug(?) allowed me to increase my storage for almost all resources into the trillions.  I can screenshot or paste the save file here if necessary for confirmation.

As of today, the resource production is back to normal levels.

**Comment by darkniko** [comment]
Thats cool!!! send a link to your save :D

**Comment by sudokuninja** [comment]
N4IgbgpgTgzglgewHYDkCuBbARtEAuEABgDoAWMsgAgCEIAXAQxABoQAHAGwZgybwGZCQ4awAKAZQCq+ABxip4uB0hQAwghh18ARgBsAVkL7d/eZIDiCDgBN1mnQaMmzkqAyRxMdrXm3aA7DIAnP6mIBKSACoATPj6ZjGKytDeOqQh/v6kYRExljapvumZWTlSMa7unhiF2oRB+tqkunIgABYQDHS4eISsHV3Q4mwMAMYQALL0DByF/oZC/Z3dUOYQNRo+LSLty0NKcKPIhfpBOwMrkQgA5tccENb4AGYzMBCsnNy8dIc6/KQfLg8LqHYZjSbTWabfDRGSNfyEAzRIIyfyAr4g0ZJQ7HaF4aL6f5wwjRUiotHsIHfQ5TboIKBwbqFf7aBYGVqfYE/UZXW73R54OhQNDvEAQJDQa4AT3wumEC0WICwXRWMt8QVYyroqtpM2ZRn8DU1KugUrWG3sAgNRqVJqgUrB411UMt2hk/0yxu1ppiMJRXtVMWdtTdDUMpH0sO0yP4yMVWsD0XNIeC+nDkZk0aCsbOfVt3vtiRGTshc20/FCJP8enJpwReYTPv4+DOAabwbxyOi0T0pP4Bjbhf4yc7QW7veyA/zgf4johjBdPn4gmEedGbQYUCOMwAokhrnAJToAqx15vtxw9weJR3LUToi0ASAz1uELv94eICPXVly6RoqeG6vu+14QAA8mgdBsJB+BPjAVibqI7gQBwx55vBXBQEhEocLePh1P40QrqwGGIchHDfvhBJ1CeICkVh5EQVBMECKwGD0BuEriIwPzIDohDaGxHHIdxILIHOeEOLoWT6E+7F0JxECibxSCRIyVReHi5a6P+Mh5kgaCjPcm7KYgSBxPEIAGUZnRQKZ4nFvOep4hWmZugBVmGcZdk8WZamMB4mmusERhBIJIC8Nc1KjHEeaRdFEmlqOHrVmxDBRZilH4PwkYBASaUZdySQqIURGkIEtFPGg8DIAASp0ox0PScRPlVNVIPVYxNXZjmSXgjTGKyrRtWZnWNfS/kaRaS7ZKUw3VaNDXddiRxIKV+iBIQhqsAgSiyto2ZuqQW2BDIxA9iEO1KNx9LpRAOjVoaMi6GFMjHXmu0cCgEAAB50DdbjXPdAjZHW/DutsebQRgbD8VDmBsH1MgPhDHwI1l+LzLo0ZozDABWYwANb4Kl7AIwToyE31PbVnpuNsBThMY6Eb3hdDDNE2BSiFNkk704zTHQfhH1KAAYnAKECoYV0cOLkuJQupWZizMtyzYk2BdN2V6GGqsSzYK24paEaBKSMu1XA1yxeblsK85lrdpk4MeZ9FvXBr1S1CEPa6LoNvXLSED0oyECFMENNCQuaFyhWDT/GQcpvXJkIA3dMJZOSZwvaQ72RzM31/anQMtSEaaZuDMh6XFn5QNbEU131fihGxNcAOoIAgth4voz1LAwYBSgAIgyHCob0fcD8PSi4UlrpyhPQ8jxR6yFPPuz94v09c4udcDJPS+CyxeisAe1wMFPo/8Sflvn0vds73ghG6B5p+39PGOV2619nxfHCG2tWlET/FYAARzQO4OgmBf5w1AeApAkCMC/3vsyIIQQTCZA2rAiBUCl75C7g7DaL0ZJ5jAdgxBS9A7ByZFpUkJI0zhSBhgP4RF/AmGetEUILRzqxhPusIuwNyxzTjuVaIipGEF3+t1NOmMySZCzkEHOYj1gTBrjAkAjCVESigNTRECINTqOUTXDGgi9J+xAAwawYB3DjGsNA8e5jLHWIeL/RuojWAWKsUgGxv8MaiLzB4pxtiD7czxGvAJXjnEH0gkLWQrBrBwAYBgZAQTp74DzPExJySkG9VnjNRUGSklIBSaPD+OwClZLvgcVaPMFink3FgKUEo7GCDqVABpTS745MVi5X2s1WntIgD4leeJyp+GXP0xpgyKH0CDgyahrp+ANH0S+C8JMTDg1jHpSMxBpIZkAueN8f8pHF3xE0DO/YySKhWYciR/DYLInSNJZEco1xAQvLyO4Dx8BChFKwAA7h3awWA0BQC0VfEAALO7AtBdAamllIVApBVo9undageSqqC8EaTWAYqQOCJGeZcXghRfgnwx0cVIvBNvWoioiXjBJQASSQDE3w6LKXjEPj4VohMlDmXsTyjgSBkEuVqSAAVSAMbP0VOK/+zIq44vtD0aWIAniKp6vi3JOg4TlXmAqqU0AAAy/cGC1GaCzSyqr9XaJmVQ0OoSNrg3+YCtC2YWgxh0tWYghgzEIrub4Cs2RUwej8U6zutzjnAw4bIw0iIFG5whYC0YkEVh1wRUmgsjcAhhDTcm6AJKTi9xAECFIuba54HJUW7gJaM2avxA+Dyxa1CloxsdZula3hNoLNSrSmY8yNtUKWzlOgPLWAgE8ekEBNA9HSWOidU71Ulm6XeMps6oCTsuOpTWpV6xxNXeu/YHAcQAIIYqQ8bUegtJAGe6qQwun2x8BwsKrYr1IHPVAbtlpZI5x7Kwa9HbKFzLtZaOEyqYCjAlhEuID4to5W7NEL1bp+B+EslwLAajUP5q0q5RErBUO+N0fUXDDAsDUyxjjStWBfS+EVKhmImHLQtDOIIMxtGkzDIdmR7sRHKPREbth7GDbiORGbNR8KtH+D0fwhGSMsZfbceE8zaMJspzibhawkIEY+1CdIH8Fj2nJMwlOHCUIxh5hhFo6QYxhDENoNJhZvqiyc7VhRFkHSrAoAIEpvQbFIAPNeboKLEUY9TgPhjkEc6pI0F+A8n5wm9BAsoQ+fyb5wpRTrnWIcGYoguDwL+K8jLowss5boNTY6zR/hkkAgVorEDjF6Q9D3Mx6WMCZY4NliBH6qIkiQ4RJ8CAfpwHiTAMSfKmjhX64NuAw2VJIyIrCbIFYzETaGyNjGxgFEbOXJZZbU2Ruddgr7SMcjywkTvWPFEHC4PuS9TpLacEzt+v+DlEIGzIanY1QucNt0TktGc+VaS/ZFTyUUrBGD44e6ki9aI7MllgciQjfchRtnnlA+EhKL7gNgZwmCNmCMY5FQ/ACtUbWT8RHIdZOdU4rBCdTT9b9g6/3OEE83dUDH0jBGBuEYRMRVgBQtGfiYQg71yr6B2V/dRvO6eogZ6wpneZri87Zycjn4MuchrokoFQsEziV1M92RZxAwqOZIproYCO8DY9Qf8ELip4DJCgErgRj0UQvSOrbqpfFqOoPHG6y7JBghmLt0ev1Kug0iPd4e1ajv07RvkYouKHckDtygHFstdQE/IGT6nyVIVmNsUT3Yy6EUC/TKXcLHKOVAj5+QEMrWeBn7RiaGYpJNfgkP1IGN7I4UW9IAAIrgKgPaWUHke/983PaYVDsFEsxH4nsfg+zTsfwm9HsJ3i/IHnxPj3x6qLBHKvoz4Eo6A7h+oVqx3UHAUkP/QE/Z+ugTRZ0FJc0kGhuhJM9A/OWb+n+Nd1Bl4x9QCRwYmgzgHx0Qj9b9f96QAMQ4eZCBK4K9+xLIrEk1MBsp9EUC0BMBJ8H0DRWBMDMB8MNoPIYBDIVJIDz9mp7FSDGozIKD78F0nIH508SIyC6Cf9KDVgl9ZBbc2DkB6Dup9t69bdHJ1A/ljx3sACEA/kcDZQ3oKQYBRDpCPYn8SYEQwhFDwQxDZUtJosKRIBct7EDD/ozsTg/E8xjCAAJFCT2EZesCw8UErG1QDFBPMX6TgCdMtZVdwjgTw4xLNZ9TQxdGYOxdCM7bJD7e9GEEQyIjgWvMOGI4IuItvGlRUNgRwt+S+exdI+BTIv+UwrSd6KGDI+I3QnYHIxgJBbfE4F5anTdOxOoDyGnJACIpImlcMNBLaVoZonxXnGpEkaMOUSyHo0vWZWAwBIQERJ8awDzQbaIuJWY6wWQ/1CMBY3aawWkRSZkfsXdTQDzK1HzUdPYhAK1ZY0VI4oUE46AKzfJddfY6AIQ9PGdLoNoUSMtZ4hSN45YgIFdF4r403NQXQ845YV4xgOyaovEZGRULqcBC/ajDyGEhg74gSasZoVBMxRE7qaww9VQ/EbGGNLsdxRqWE6A5w8Y10YQKYkiI4FiNxOiGkkw2I1eQiakhASCFQuvP8SQiAI1DtHzIInkqtRghzUDRyXk647gvAXMbk8U99EJV0dXHAKABSPgBsaAFU74hoeMdUjcDk2oKEtU5UjcHQ10J4upJAJAT3Fg58dwS0oVAo00wiSsPwNcW05AR4rsBvPpG0i05AGA+ZHwasAwV6TUXwv5bqdcOuLAMMiM14h0/CVheA0M6Q2MvUkVH9ek+kdLd41krcDoYU2tUVMDLM/M4xdXYsvMh4+U/CWo8xC0uANoJQBgmEBE+sxsrgZaeMmEb9fxNsps7qSVLGJ8W0hs/s+kYqFILSOOMxI49U/iaYyddU5Y46WDVXGdDtf6CEu8DaPwZ6bIXY9U/0oDLlLaIXT0XzRc88NoSQJAXwrzAUH5UUNdN4K8r5PAAAbRADQFvM80JjuVYG/LvMJmoG4EOD3ElBlAAp/MpnEAQlrigqAomDGEbIlBgBYC/OgsJm3nQrQDYGuDcFHXqnghBXGEiAgEjIQt/NgswnEClCnSYUospiNR4xwrwoIogCvE/DIooq/LYosSUjgu4raBwswtql/PiyC19EYsJmYuExEqAsHjuL4PMmkpAoLAljQtUrtA0qkowqAva2BHkt/IMt4DUmgFiGkp3AwBimkqPKMspiPLMqgG0HsqpjJO6Ccosr0t/MHjor4mkt8vgntPzPumkoiFctyC8sAt/Nkp0y0vUsnTkoAF13ErEmzozgZPzoqYKEctL4BRhwKoBpRXLsLpLqLNxXKkL1xPxNLeL8L+LOKJQhLWL6rR1yqoBmqyq4LaL6KWr2KiK2StwIBOrvLKZFK9jlLXLZKorRLxKAtJKZqgLZLmx4qVgNLXK1K1rErFrjKqQmAwq9rPLXKrKbLRq3K6RANKr3LhqJZnKrqLqQ4jqAq/KVKzrAqHIQqprtMIqpANrtLEqVqzrIqQAUqQBGAsAYAbygK3zPznzbJ1xIhiN0L6IerugMBEa0MnUiloAMb0LDwVgp1R5Nxcbf14FoBCbMJcbQbnzBrxhIbMKYaxQtFpQUB+50Lrl842aZZWawB0LYsJLEsvKjgia2A3gmUtF2sj9kazseb0K4cJRRBpDcBI5FJZa6iidMA1aNdI9kAtaFcbAta7cVAtbhauBRbwJIJoBJbvMKV2pFa/llb2gpQZibhxQtbGwGRJ10LxQIL+FqB+t0KOgcSMAta2A11wM2SYB25saHcuaE0Y7RZfD6RtB3b/qYBdLDgIBDarBVBHDHaMJc6yaOqEA2ASavy3BNYtbrJvJ7bHafair6BDho7R1Y7ebqdyK2hm7oAtauArEtb4pMRa74LKQMRQ7DrbqvL1hRgkJi5I4xjuh+7rqdwJhVA5brqnKXK57bUnqQBrAXqZ7Qrd6XrhhPqt7AMu7W72aEAMAMBvzMsVIL6tb+a6BH646IE4BvgVhX627nxr7b6PBCsH7klu647n7v70L37P681gHL7Tw/677AGzJwH3M5rkG6yfgoGoA0Gjgb6EGRs0GwGYGtbIG7RsH4GAH8GiHQHUGqGf6SGCwyHcGKGgGY6n6aHWG374EP7SHaGr6mH76kHeGUH/M0H6Gv6hHf7+HEHM8JHCGOG6GuHMHGH/6BGZH5G+b2GW7iHFGeH1G4GpHKG9HfNNGQGFGMHdGtG46cGVHpGk9ZGTHYH0HuGGGJHrG8GWHLGf65HPGIGdGXGjG3HmHBGjHvHTHfHzH/GfH9GbHDGonjGRGJGxHoGAnyHVG7GQmHHtGInxGUmDGPGwnhG4sX7Em/Gcm4nAm0mCHMnOHsnknynUnbGqmEmjGkmsHXGGnYmCn4minRHSm6mumKnGn7Hmm4nWnlH3Hgm4nQnHGxn2m8nJmunpmsnnGymBmOn8nHGlmamVn+nHHBnOnNnqmzGdm2ncmYmNm2GRmunZmzmJm1GpmjnwmTnxmgn7nFnHn3E+nTn6n5m3nDmrmZmvmXnKnhmemSnanvm1nfn0mHmAXlmlG5nzmFn/mwWWmgXEW7mYX3m4XtmEXbnXmsWUX6BemIW0GAUE6k6oB+BDawSz4F6rH1nkXLnUXRn0X8WQWMmcXjm8WfmkW/nmXiXwXnmMWCWmmWXrm2XeXMWxXBW0XSWRWOXYXxXAX5X2WhnOXlX4WLGoW+XCWBXim5XhW1WDn9WSWjWpXRXQXZXWXVWLXFXsXNXcXtW9nGX+XqGuWnmeWdXpWrWDWbXzWunOReB+EbzGRaqg2GA/aA70RgQQ2PA6B06vKPadLAb9mLn3XHXuXnWTbXW9WM3rWJXbWunyWW7E6O4oBogc3oWZW/XC2A3HG2B6QFwxLr7ZbQbLT/aoAW78BPz66Wa2bqa5qjVvz0sHzUt271wobxKx3fkIprqp37yUtZ3gVtRkAYBLDBtR0+Ve2foPC10JhE9vbd3fC10AA1cUaqI9vdyYTcWqnwidAAQXnXWNoA4C0FYHvbXQvvsles/YgAAClcKQ5h6/3xAugkV0Kw7yLEBqpRAPN8LJ1w3w6YOo6YHqBk1/KxRj2J1stIIEAr2T2IAABpNAOAdIqAV999rD696iwulNIkn4c/CAOD6DyOi+725mxu6e+D58u9zj7kC+9D1d167odcODm4Xj9C0TzutDjD16rqOAJjwqoGATmBiB2gpjoS9j9zS8vMky/ai8l8vMk6vm3T9cd616+See5jnjxDteh67oQTuT9TxjwYI87Ti84FJQLuG+1DmO0zrzmwMSgFgL0jmwB9yVx2hTpjxW5UmYUL7zt4ul+6UGv9gUT8nvdCgwy9tKWACB59wbSj9Ckts3EbdCvGID+juicD0FSDjgPD9CwmUj8jorkiHOvO2uUGkFKaWUN1aXNMEIcLJ0gCiu6oP1S3XHG3PMbryu36SRb7J3AIF3V6eNaLwYdL9gZDyOjjyULjqTju+z6zvhjAWq5+z1u0SDptmYFthiuiWlwYEGk+Bkfz6jJ7w8FutMz9N0CkfC9729JkwBANN7mOvBE4b708NALAX4exJNKH0YSoLdSEtcSH0ELs6jHYWHw4R41cD9pABkbMnzcUfH/M74nKRUInw4fMz7h9FcNwvHyng9I9UqH4vMcOqUGyMtS9Nnjn745+CMRZHT0Ydn+4a1FUiUMOURRvQX4X2Fa601MkczY1P4ZjLadPJoCLJoQTKxcbnuK3PHdXXuhgaPXwZ3D/N3NcYUcDDKv4U8S3uADK0nvSZZO3jK3xDvKcObtwcaHMrDoULqcctHpoHYT3/3jqx/Tk8wj9v6L35aLcrYYP6PtAbt+xT3pP/7to0JXMNwxPj78Pk4ewqPn5Fuk0pcLP/AlCXCyBZs178ACvtgKvzsgHy0TIGMZAuvhv+kUHlycsFfcv+r+vkk0X6zr2VYp2l2oGPlbMZ6asZcMKeDQga3SyNoZ2+D8UP1HscqBXnSeVMf1f1AObv1f8JHJ5TotcKwe4b30HOB0ecixvjPjjVkNMa/i/7qanmEPKHOAqKW+xSKI/ZEnf3/vQDf5SlaygAugF3wYy1lQ4KEMeG4VzqjwJygJO8NzjgEwCIBM0dXNAIQFx9DMO/FClu2hRWx+oeYfAeKEIHLFJec/MAu0D+5IBCBmxZCLUAdQL8sg/QWgfQLl6Qllw5UJYMHTiCZA/A/4HMOr0NAKJeBY3c3AECW5m83oioIOqzgP7m4nsYMCGDvxdpHhfA4UdQUpDR5EQ0EM5DzFxBwEm9dy1OdwKnh8wBRU83xaDHmCsE408+gCdXPYPBI60d8sgeNDgyg4wB4IPvLwbxwD5N8tgtPfRt4N8HADA0Vya+mEPHLGCco8aGADyhvpKpwoiQj+uxALJl5soXYcuHBCSEZDgB+uRzNtDoj5DZeDnY8i2A2x5hM6JMWMPCEaAuZYwxAJTL+nGAh4A0quQkOHhqHjBjeUaTOLGnjxtDmOhwYmFaBGGiAxhyxJDKFH0SZ0phlMDGMuGkhtpM6oREYa0SYKlRFkp6cYL/EKHRg9hUyaeCXx0Cn8FUEACAAAC9p0lwm4en22G6EC+KqNdA8LD4a068z0HYKqiuG3DXBTPPEJWCBxQBRYbw24WogwCgjwREAAzP1DgxwhRErCNiNCL+EQBsSthV0GODHDGYR8qIh4UeVKgEYQyc7CoX6G7CRhmgQuFoc9EaCf9SR1ndfmci36XI4o11Y3kf0eSEQLhDI7ejcE+QztRQYdfGncM24ijMhURdHuUWe4rAzhxAnYA7TQyaDwoiomYS9EaxbYXo/yCAFgAR6Yj8IY4AwNJFjR5hVRxgvxJGBJB44ZyL1OuHvSCrAC9IWQZEUfSCroCYQruHuHEmPrGDCQ7oWiPaL9KcCHYrub0UFX/yVC8SYUL0XRDYCfVfAJEP5JuCYTED3Mh4IgdJCIyaBxYP0B4JIDYDWAHuRQVBLJFdwKJyMyFCWJAHYjwI0KeAUACoHaiwRceQodavWPMTrgAA+oQGbEdi2gnYlyuWiJL9jYgQ4vsZ2JEzDkuxOmMcchU7H6Bexc43QNlGHGdj/Ai4rsTIA3H9igg24gcT2NnFdi/Ae46MCeMnGrimgJ4hcYeP7F6ATx64m8QOK3H4gLxu4l8eONEQwhVxPYHQN+NHHhQ5xREX8R+OvEIkuxD4HzIBIfH+JwJb4gCV2MEBfjxxSGYCXONjCoSEJImeCf2P+AYScJ14mCThOXH2I0JD4sCThOfHkSJxb4wiZ2OOiQTpxg42if+Dwl0SRMzEgiauOaBIS5x5UViWSH4lviqJhgViZGAYn9jCQPErsbJFEnETaJG0KSRJOfHySaJq4uUOJM7HPwNJOkbSaBLUlyS1JyktSUJNXEIgNJhEcyexNMkzjaJrCcydBNMlGTxxekDSZmFYnIxXJ147CZ2OejuSHx3kyuO5JMnjiwoikzsWODCnZhIpM4qiQ0FYloIdAAAX0SkkRfImgQ4HWIbHk0zIwExwp7UykRR3A4CDgANRIpe12xvNXwGvCsQOBCAKUsGrdTAh/IJQ1gQcQ2IcDhQapVU7QPVJ+APFmpDwUce1OLH4E+AIBXqY1IGnWARMw0g6K0C6lzSJp/UlqTOOGnAJwAfAf4EtPfRTTrxw0oiKNJhD8BtpTUlqcRLWn6FNp/gXqcRnprQ0BQa0+qTTTKl3Tp2+AYafNL4AyBepHdIivDQ6APTwAEhDaceHqmfA6aJ+a9oDMqkeQup0QeqSV1gDoclAPgNaYdIEAIyYGMAB9hp3W7vSgZrEEGRjJIiIc/IH9YGLNMcA7IO8TxVcMgTGlUydILpVcEIH0ATT2I7WfVNDIcCGBqZzMlmfTJ5kkAmZtM+UPVPHRQBMG+AOiG0Cbas12I6FLALzj3DEZkseAF4BwDeAm5R0yoQEjDF45vkNZWsqyAgB+BPA0mMAFWRlUFEnwGAh4ITk1CQDrtN24oZ4K8FFAKR1gwMW0G8AgZ4cwOkAJlCsCsRjxaedUp6ZOlprlThplkMtKAD7ZqhQAfKabm7M1kQAwZe1fGcnIAqpy3g9UmbsTnbHZyvyuc9OURi6lJyfMaAUufVM+hZyq5NcvOGPErn2Jq5goVLPVMYT1zW5S7Muc+DeSHJu5Kc9We7Mxmdwh5Oc9uSKHqlB5VoE8kuSPLTkzyzs88tuUbL7ny0KZVkBuYvLznq0euRcneevM7m85V5jc7WlrkPk9zd5fc5fuP1dlXzh5x88QWgUfmTzn5V6cYGfJvn1SrOtqb+R/LAwQYv5b8hecfOSmagwu8SfcAVMqnhQ4A+MhOZECYm48IKVGOnmgqslM00FNk1BUVSlCRBOJ2C/BZEAMkj1gQyCnzBG3QUjcpolC1uaN0wA0Ly6dCrBQXKYW4LK0ViehVpm4WjjeFDAOSvYkN6RBOFn0HhTLGYXiKsF4izhfJBmASLSRCi/hU3KEVsiFwoinzIwkUXaKVFBidGlgu0WcKOaHARRSYuYXmKsF5izhQikUW2K9FtirBbYs4WzzkAii1xapD0UeK1FJuNwZouoJnZ3FgSrxYEqwUClnQ/i9RYpEUWbzmFsSrBbEs4XNFqgii5JUwr0VpKDFlg8PpEpPi84dF+SvRfrWsA+KJc6sFxQCXcWVKvFlSsJZUs4V3y9+iixpa7U8U+YWlE/UpR0vFC5LdgwdZpTYXSXtLBlWS+xPII4U+ZM6iiqZXoqmVYKplci9eigt5GAZmFQC8UKRWWXrKIkay8DBsuGpYLn6CWUxcsqOULU0kECsGgdwqnASEF7YzQAt3zGtVmOmc6ghGieXsU9Rr89CO8r4qjojUXUn5Y8r+XgQ9oby4Fc8udD8lflzy80NCohXsVVAA8+LuCsxwfL+KJKeFWipBX/wsVd0dFW1RXmor8VIKhgRoKBXYrnlHJPFUDAJVfhT5xK2lTioBI0qIAdKywiv1aWsr2VIy7lSCojF8rIV11KuZhRAr5VlOaoabphW3jic6a8AfcCKqArtVFVv5UqUNSqooVypUqhSkpVoKe5tVVFbqnRTRoqqmKQmPRdlRkoMBS6bC0VXaAIXLLLVm1H0BartUFgCFtq/SodUdWYV9OzCy1SZ1bmYVHKPqxCuvVdVhqKhpSy1RZ3EBJjJZpqwmLGrjHQBgY03EFWqtIrXL01zyxqsNWzUAUcVglAtWKCeDmy9lXiKUH9KvI6BQMFa8YDuDLWHBgFVaszsJSlJPgE5ja8tS2urV5lYolyt4NqHTGwLspVpFsflPemXLxRFNCqhVLHWjY0o1VVCogo/AaDQANJQwvlG1pHoWoWaSMGfRDj8R3QPA3flysxjwFpIugeqQwGgD4d2xm6/CJZCNo9AO8LfJ8LUPLQBBesvCFMW+t6wzzGyksfGY+rrjhLIQR08qMrDsHh9souUQiE/yUVjwYwOqcsIOrBKZTkpiUoAA

**Comment by darkniko** [comment]
Ehmmm ok :D Thnx!!! i had more achievements but get Trillion storage is waaaaay better :D

**Comment by sudokuninja** [comment]
I saw that this issue was closed.  Are you or Darkniko able to give some
insight as to how this happened?  At my current rate of resource
production, it will take pretty much a year to fill up capacity for most of
my resources.  Thanks!

Sincerely,
Mat

**Comment by darkniko** [comment]
Can reproduce the bug offline. But theres no point talking about it anymore ..

**Comment by sparticle999** [comment]
'As of today, the resource production is back to normal levels.'
