### ISSUE TITLE
Updates TAB

### ISSUE THREAD

**Issue by darkniko** [sparticle999/SpaceCompany#148]
Is there an Updates TAB currently available IN the game?. If there is i can't find it... If there isn't it would be pretty nice to have one :D

**Comment by sparticle999** [comment]
what would an Updates tab look like? A changelog?

**Comment by sparticle999** [comment]
If you do want a changelog, you can find it in More -> Links

**Comment by darkniko** [comment]
Yeah that exactly. Ok nevermind. Thnx anyway. Hard to find :D
