### ISSUE TITLE
Faster Dyson Swarm purchasing

### ISSUE THREAD

**Issue by sudokuninja** [sparticle999/SpaceCompany#150]
This isn't a bug so much as a suggestion, but I have enough resources to purchase about 100 Dyson Swarms.  Is there any way to build in a feature where, if you have the prerequisite resources including rocket fuel for an entire Dyson Ring/Swarm, to just buy them outright, rather than having to click on "Buy Dyson Sections up to 100" and then "Buy Dyson Swarm"?  Thanks!

**Comment by sudokuninja** [comment]
It looks like you added this feature!  Thank you!

**Comment by sparticle999** [comment]
No problem. It was needed

Sparticle999
