### ISSUE TITLE
Dyson Sections (reasoning)

### ISSUE THREAD

**Issue by kreezxil** [sparticle999/SpaceCompany#151]
What exactly is the logic behind  having each subsequent Dyson Section cost more than one before it. To only have the cost reset after you purchase a ring, swarm or sphere?

I suggest, that you call it a warehousing fee.

However, again that would also make no sense.

Why?

If you as a civilization are sucking energy from your local host star. It would seem that you and your people would practically be donating products and services to accomplish the feet. (This a Utopian concept).

On the other side of the spectrum, imagine you are Evil Overlord of your planet, we're back to getting some things for free like the warehousing. (Dictatorship, warehouse this crap for free else your family dies).

So mining and assembling the stuff should become more expensive, it should in fact become cheaper, because you are getting good at it.

Maybe add conscripts to the equation to justify it.

Because you are building Dyson sections, it is possible that rogue elements (green peacers, tree  huggers, druids, rebels) don't want you bleeding the Sun dry. So you have to hire or otherwise obtain and keep motivated a military force to protect your Dyson sections and possibly other endeavors. The more sections you have the more skirmishes you are obviously winning because you are dumping so much extra into the military side of it.

Then again, maybe we should have paramilitary elements in this game, where we have to defend our stuff. And then you can take away this rolling need to make some things more expensive when in reality they are less expensive.

Not sure which country you live in, but in the USA when you buy more of something, it becomes cheaper. It becomes both less expensive to produce, and less costly to purchase. It also becomes easier to produce and in greater quantity.

That concept is clearly missing from this game.

I think having skirmishes, battles, and wars, while doing this, if only with an AI component would justify the higher costs of things. Because in War the economy practically flips, and what should not be, becomes the norm.

**Comment by darkniko** [comment]
I understand you completely dude. I really do. But you can think about it in two ways.

1st: As you said and like the game shows at simple view each section cost more than the previous one for no reason at all. Thus it is not real like the real world we are living in.

2nd: Each section cost the same cause the final price will never change. EVER. (And that is not real in this world we are living in).

Idk ... But its quite interesting everything you said. I think all of this would be good as for content of the game. Still a pain in the ass to code all of this if you do not know where you are going first.
