### ISSUE TITLE
Show Gains/Cost when building workers/machines

### ISSUE THREAD

**Issue by lucasfamelli** [sparticle999/SpaceCompany#153]
Suggestion: Show the ratio gain/cost to decide a new worker/machine.

Example: 
![image](https://user-images.githubusercontent.com/9695740/28126600-4fbe0970-6700-11e7-88ef-9bccb094892e.png)

Miner produces 1/s and costs 108 metal and 54 wood.
Cost ratio = 108 metal cost for metal/s and 54 wood cost for metal/s.

Heavy Drill produces 16/s and costs 12828 metal, 4810 gems and 2 e/s.
Cost ratio:  802 metal cost for metal/s, 301 gem cost for metal/s and 0.125 e/s for metal/s.

So, in Miner is more efficient (at this time).

How about showing this calculation right beside the costs?

**Comment by Pestilenzius** [comment]
This would be an awesome implementation. I do this in my head, but it would be nice to see it directly on screen!
