### ISSUE TITLE
Kongregate 0.4.4.6 UI issue

### ISSUE THREAD

**Issue by Verpa** [sparticle999/SpaceCompany#163]
Hello,

I have been playing a while now and had no problems thus far. Now, since 0.4.4.6 on Kongregate, I get an issue when opening my save (attached). When I open a clean game (delete the save) nothing is wrong. I have not edited the save in any way. Also is a screenshot of the game as I see it. This happens in both Chrome and Firefox.

Thanks,
Verpa
[SpaceCompany Save.txt](https://github.com/sparticle999/SpaceCompany/files/1163091/SpaceCompany.Save.txt)
![image](https://user-images.githubusercontent.com/30323652/28429300-83588f9e-6d7c-11e7-8d51-bd759a1be613.png)
![image](https://user-images.githubusercontent.com/30323652/28429330-9f4913a4-6d7c-11e7-8c0c-05a7b1ddc507.png)

**Comment by mikehart526** [comment]
Having similar issue on github site via chrome.

![image](https://user-images.githubusercontent.com/1630539/28432018-a16a71c0-6d43-11e7-8b32-3ea54a5c3bd0.png)

**Comment by sparticle999** [comment]
Until I manage to fix the issue, try a different theme. That has fixed other's games

**Comment by Verpa** [comment]
That works wonders! So easy, thanks.

**Comment by sparticle999** [comment]
Can you try again? I think I've fixed it

**Comment by mikehart526** [comment]
working fine now
