### ISSUE TITLE
Rocket Fuel Bug

### ISSUE THREAD

**Issue by Maximeter** [sparticle999/SpaceCompany#176]
I was playing the beta and realized that when I tried to turn on rocket fuel it wouldn't work.

**Comment by sparticle999** [comment]
I haven't been able to reproduce this bug before, despite it being commented many times. Do you have errors in your console? (Ctrl+Shift+J / F12) Can you send me your save please?

**Comment by httpnet** [comment]
solarSystem.js doesn't move by an exception.

The "let" which doesn't exist in an old browser parameter.
solarSystem.js:124 code:"for(let i = 0; i < toAdd.length; i++) {"

This has the same problem in #116 and #126.

Also "const" shouldn't be used for an old browser.
core.js:72 code:"const precision = 100;"
