### ISSUE TITLE
Column sizes changing in EMC

### ISSUE THREAD

**Issue by lucifer6642** [sparticle999/SpaceCompany#200]
When you spend all your energy in EMC, the column sizes shift as the size of the contents change.  I have tried to show this in an animated gif I have made. The crude red lines show where the columns are when energy is at zero and as you can see, the middle column header moves left for some reason and the right hand column moves right.

![space_company_column](https://user-images.githubusercontent.com/1088245/28898552-78905a3a-77de-11e7-837a-7b749fb413a2.gif)

**Comment by httpnet** [comment]
When this adds a specific style, a problem seems to have been settled.
It won't be a perfect solution because the character is piled when the width on the page is made small.

.table-responsive > .table {table-layout:fixed;}
