### ISSUE TITLE
When i reloaded the web page lost all my progress 5 hours spent

### ISSUE THREAD

**Issue by junkychap** [sparticle999/SpaceCompany#209]
i reloaded the page and my progress is gone and is now unplayable cant click to collect resources, it's broken on chrome but works on firefox

**Comment by sparticle999** [comment]
Are there any errors in the console? (Ctrl + Shift + J) if there are, please screenshot them and send them to me so I came help

Sparticle999

**Comment by frazer380** [comment]
Make sure you have on autosave, or save it manually. 


... 5 hours on a clicker game?

**Comment by darkniko** [comment]
Ive never had any troubles with saves in games if i recall correctly. But i really do not want to end in this "lost save" situation--. So i always save manually and export to a notepad everytime i close the tab.-- (Bit of much but i will always have my saved progress if i ever encounter a lost save :) Besides it takes almost 10 seconds to make a backup save .-
