### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by darkniko** [sparticle999/SpaceCompany#219]
I dont think its possible to do more than 345 achievements with the current resource tiers...

http://prntscr.com/ga9a43

http://prntscr.com/ga9ac7

http://prntscr.com/ga9afm

**Comment by sparticle999** [comment]
Yes, I know. It is hard so that in prestige runs, you can get more than you did before

**Comment by sudokuninja** [comment]
How did you get 1000 scientific observatories but not 1000 of the other research facilities?

**Comment by darkniko** [comment]
i dont know :D aaa

http://prntscr.com/gbny5k
