### ISSUE TITLE
Retrospective Dark matter calculation

### ISSUE THREAD

**Issue by JetamJetam** [sparticle999/SpaceCompany#222]
Hello,
I have one sphere ( I cannot create more) and 16 swarms on Sol Center and I finished all wonders ( wonders tab is hidden for me) but I dont have any dark matter. I fulfill the task before dark matte functionality was released. It will posible retrospective calculated It ?

Thanks.

**Comment by sparticle999** [comment]
Hey, what do you mean? What should show is a 0, because you can't reset yet, and then a number in brackets, which is your potential dark matter gain for when you are able to reset. If this is not the case or is not what you mean, please provide a screenshot for clarification. Thanks

**Comment by JetamJetam** [comment]
Hello,
Now I understand. Everything is ok. I see the hypothetical amount of dark matter. I'm looking forward to a new functionality. 

Thank you for your explanation and hard work on game.
Sincerely Matej.
