### ISSUE TITLE
Can't gather resources

### ISSUE THREAD

**Issue by LeoShishigami** [sparticle999/SpaceCompany#23]
Decided to try out your game by I an unable to manually gather any resources, I've cleared the cache and hard reset the game to no avail, I am on Firefox 52.0.2 32bit

**Comment by sparticle999** [comment]
Occasionally when I add new features, there are bugs that stop the whole game from working. I see these a few seconds later and fix them within minutes. You probably just came at a bad time. Try refreshing now.
