### ISSUE TITLE
FACTION STAR SYSTEMS TAB - Military Fleets are Nonfunctional

### ISSUE THREAD

**Issue by JigsawJunkie** [sparticle999/SpaceCompany#264]
Upon traveling to either the Hyacinite Congregation or the Carnelian Resistance, the tabs do not work.
    
Regardless of the size of one's military, clicking "**Espionage**" "**Invade**" and "**Absorb**" has no effect.
    
The chance of victory remains: 0.  System Fleet Statistics remain "???"  
And no additional information is revealed and no new resources are gained after attempting to Invade.

**Comment by sparticle999** [comment]
did you add ships to the active fleet?

**Comment by JigsawJunkie** [comment]
I'm not sure what you mean.  I had 10 Scout ships and tried Espionage, but it did nothing.  I then tried to Invade.  I clicked the ++ buttons and invaded with 10 scout ships, 6 corvettes, 2 battle cruisers and 5 of the next ships.  But nothing happened.

**Comment by darkniko** [comment]
same here. The only action that worked for me was attack/conquer... Now i have -10 with both of them :/

**Comment by darkniko** [comment]
![1](https://user-images.githubusercontent.com/24360651/30641221-a7ddf936-9ddc-11e7-92c5-20720a0b293a.png)

![2](https://user-images.githubusercontent.com/24360651/30641254-c661e282-9ddc-11e7-9ecd-ab9038ac4dcf.jpg)

And now... where do i check the mission was succesful or not:_ Is it instant__
