### ISSUE TITLE
CAPITAL SHIP for Invasion Fleet - Cost Imbalance

### ISSUE THREAD

**Issue by JigsawJunkie** [sparticle999/SpaceCompany#267]
Did you intend for the Capital Ship to be virtually impossible to get before the 1st or 2nd rebirth?  All the other ships are relatively inexpensive.  In fact, so are the first two resources needed for the Capital Ship.  But the final resource of 1.7 Billion Meteorite is so out of proportion to the rest.  I just wanted to make sure this was your intention.
 
I generate 2,650 Meteorite/sec - which is a lot!   It would take me 20 days to grow Meteorite to reach 1.7 Billion.  If you lowered the amount to just 1.6 Billion it would take almost 40% less time (because as you keep doubling the storage capacity from 419.4 to 838.8 you end up with 1.677Billion.  That's just shy of 1.7B so you'd have to double capacity again, bringing you back to zero before ever reaching 1.7Billion again.)

**Comment by darkniko** [comment]
http://prntscr.com/gkvc5d

Once u reset with 134+ achievements u can get sphere in less than a day >)

As u said 

http://prntscr.com/glovh1

This was my meteorite/sec prior 1st reset. Achieved that long long long ago....So i had nice meteorite reserves :)
