### ISSUE TITLE
research Energy Efficiency 26 to 50 does not stay

### ISSUE THREAD

**Issue by omagaalpha** [sparticle999/SpaceCompany#270]
Every time I reload game when I have research Energy Efficiency between 26 to 50 it reset to 25 when I reload game. The Console does not have any errors in it.
Edit: I Have the dark matter research that suppose to allowed it.
p.s. If who every work on the fix need my save I will provide on request. :p or you grab one that post in early issues that is now resolve https://github.com/sparticle999/SpaceCompany/issues/259 which had that bug in it at the time.

**Comment by darkniko** [comment]
http://prntscr.com/glvca6

**Comment by omagaalpha** [comment]
First in case clear I had purchase dark-matter upgrade for it.

Second thing it happen because loading order from save.
Tech is load completely which cause it think its max 25. also check current level which is 26 check against the max which is 25 so reduce it to 25.
Then it load dark matter upgrades then change the tech max to 50 from 25 while current tech is 25.
