### ISSUE TITLE
Storage upgrade Silver not working

### ISSUE THREAD

**Issue by daschuetz** [sparticle999/SpaceCompany#275]
Right now I'm on 25.600 Silver and want to upgrade my storage. I have all the ressources needed (see shown text below)
The button "Upgrade Storage" is clickable but nothing happens. Have tried to upgrade other storages, they work just fine. Have tried reloading the page, have tried exporting / deleting / importing the savegame, the error stays.

Message within silver ressources panel, all required ressources are present:
> Storage Upgrade
> Upgrade your silver storage size to 51.200. 
> Time remaining until full storage: N/A 
> Costs 25.600 Silver, 10.240 Lunarite. 

Thanks for this great and fun game btw.

**Comment by sparticle999** [comment]
Hi, sorry about the bug. Could you post your export at https://pastebin.com and show me the link so I can check it out? Thank you very much!

**Comment by daschuetz** [comment]
Here you go:
https://pastebin.com/vKKnJEsx

**Comment by daschuetz** [comment]
https://pastebin.com/vKKnJEsx

**Comment by sparticle999** [comment]
thanks!

**Comment by sparticle999** [comment]
hey, it's fixed now. Thanks for reporting it!
