### ISSUE TITLE
Activating Technological Wonder eats resources with no wonder created

### ISSUE THREAD

**Issue by rokukaze** [sparticle999/SpaceCompany#28]

**Comment by sparticle999** [comment]
The tech wonder unlocks tier 3 machines, do you mean there is no 4th wonder?

**Comment by sparticle999** [comment]
I haven't added the 4th wonder yet, but the tech wonder should work

**Comment by rokukaze** [comment]
I haven't tried again but trying to activate the tech wonder did nothing. I'll check again when i have enough

**Comment by sparticle999** [comment]
I have fixed this now. Thanks for reporting it.

**Comment by galaxystef** [comment]
It does unlock tier 3 machines but it doesn't go from status **Dormant** to **Activated** 
@sparticle999 

> Uncaught TypeError: Cannot set property 'className' of null
>     at unlockTier3 (science_space.js:554)
>     at activateTechWonder (science_space.js:563)
>     at HTMLButtonElement.onclick ((index):3044)

**Comment by sparticle999** [comment]
To me it seems to work perfectly fine.
