### ISSUE TITLE
Improved relationship missing?

### ISSUE THREAD

**Issue by marcodelmastro** [sparticle999/SpaceCompany#291]
Hi there,

After my first rebirth I Tier 5 Machines that should in principle improve my relationship with the Kitrinos Corporation by 20. Strangely, even if the T5 are indeed active, I see 0 relationship with the Kitrinos (while I see the increase with other species). Is this a bug? Or am I missing something?

<img width="724" alt="screen shot 2017-09-19 at 17 12 05" src="https://user-images.githubusercontent.com/14204825/30599939-51f63624-9d5e-11e7-8cd1-3c38677f6120.PNG">

Thanks in advance and anyway!

M.

**Comment by darkniko** [comment]
Still dont understand what Relationship does ... At first view does it reduces DM costs or what...
