### ISSUE TITLE
Clarification of "aware" in license

### ISSUE THREAD

**Issue by Metallicow** [sparticle999/SpaceCompany#296]
@sparticle999 Ummm. The license says MIT, but it includes this line, so it exactly isn't MIT, but includes what I would call a request...

> Sparticle999 is made aware that the Software has been used somewhere else.

What happens 100 years from now when normal humans occupy the grave?
Please explain/elaborate this here somewhere, so others, such as lawyers don't wrongfully twist your words in the future.

Thanks.

**Comment by sparticle999** [comment]
Well, it’s open source, and I honestly don’t care if someone copies. But I would like to know if someone did just out of interest. So that I could play it or help them. 

Sparticle999
