### ISSUE TITLE
Energy Deficit!

### ISSUE THREAD

**Issue by SteveAgl** [sparticle999/SpaceCompany#297]
Since the before last update every morning i turn on the PC i got an Energy Deficit! message with alla production limited or negative, sometimes in science selecting a energy improvmente all goes rrighe this morning othing change. The game this way is totally unusable :(

**Comment by darkniko** [comment]
how many saves do u have¡

**Comment by SteveAgl** [comment]
I have just a save done this morning after i turned back to normality after science energy efficiency increments. If you want i can save tomorrow when the problem is on and put it on gist so you can check it out

**Comment by SteveAgl** [comment]
Here are 2 save one of last eveing when all where ok, the today one is with the problem actually I', in energy deficit wwhen last nigh i left with some positive energy production
[save 2019-09-24.txt](https://github.com/sparticle999/SpaceCompany/files/1327086/save.2019-09-24.txt)
[save 2019-09-23.txt](https://github.com/sparticle999/SpaceCompany/files/1327085/save.2019-09-23.txt)

**Comment by darkniko** [comment]
In the first save found out the problem was your plasma. u had too many unnecessary plasma machines activated. The second also the same problem too many plasma machines activated without enough energy for using them....
[Fixed save.2019-09-24.txt](https://github.com/sparticle999/SpaceCompany/files/1327435/Fixed.save.2019-09-24.txt)
[Fixed save.2019-09-23.txt](https://github.com/sparticle999/SpaceCompany/files/1327437/Fixed.save.2019-09-23.txt)

**Comment by SteveAgl** [comment]
thans, there should be a bug around because before closing the last evening all were ok, it neot show deficit, even for sure i was in. Anyway i rebirth now i will care more for it thanks a lot.

**Comment by SteveAgl** [comment]
I just saved and reloaded after some playgame from restoring ur fix, i increased in research the energy efficiency of machines and got plenty of energi. SO i created new plasma machine for only hal that energy. Then i saved eand reloaded, and BOOM energy deficit! again, i suspect that after a reload the calculation for energi is missing something about the improvment from research, and give that problem.

**Comment by Digital-Storm** [comment]
The bug is actually caused by efficiency. Whenever you rebirth, if you don't reload the game window, Dark Matter Efficiency will count as 2% per point rather than 1%, thus you'll have twice as much "efficiency" that shouldn't actually be there.

**Comment by darkniko** [comment]
eggxactly
