### ISSUE TITLE
Request for New Button

### ISSUE THREAD

**Issue by JigsawJunkie** [sparticle999/SpaceCompany#301]
On the Dyson Segments Tab, can you add a button that says, "Build Up To 250 And Sphere" right next to the Dyson Sphere module.  You have corresponding buttons for Dyson Rings and Swarms.  And now that you added the option of one Dyson Sphere per star system conquered, we will be building more of them.

I feel like an idiot.  I hadn't built a Sphere in so long I forgot how.  I just kept pressing "Construct Sphere" but nothing happened.  I just tried going to the top of the page, building the 250 segments first, then going back down which obviously solved my problem.

**Comment by sparticle999** [comment]
Request Granted
