### ISSUE TITLE
All dark matter reset on rebirth

### ISSUE THREAD

**Issue by MPalhidai** [sparticle999/SpaceCompany#309]
I lost all my 8 unused dark matter, Hyacinite Congregation purchases, Dark Matter Boost, and Rebirth Upgrades on rebirth.

**Comment by MPalhidai** [comment]
It was a giant waste to rebirth!

**Comment by darkniko** [comment]
Thats odd ... Didnt u make a save before re birthing_ ... How much DM did u have_


Sparticle,,, I just noticed the achievements are also multiplied by DM ...  is this intended_
