### ISSUE TITLE
getDestroyer()

### ISSUE THREAD

**Issue by galaxystef** [sparticle999/SpaceCompany#31]
Hi,
 you've done a freat job so far!
Trying to upgrade my Gold mining to tier 2 & 3 I noticed that _Asteroid Destroyer_ was not functional.
Searching the jscripts I found that you have the **getDestroyer()** function twice on your **recourses.js** file. I deleted one of them, and clicked on _Get Asteroid Destroyer_ button.. and I got a Death Star Jr insteed

That's all for now,
over and out
😎

**Comment by sparticle999** [comment]
Thanks for noticing this! I have fixed it now.
