### ISSUE TITLE
Unable to access Meteorite resources

### ISSUE THREAD

**Issue by athayward** [sparticle999/SpaceCompany#310]
I am unable to access the Meteorite, because on Pluto and the Kuiper Belt it just says something interesting to see.  I have no option to explore with the rocket.  Obviously this is a game killer for me so good luck finding it.

**Comment by darkniko** [comment]
How many times did u rebirth already:

**Comment by athayward** [comment]
Once

**Comment by darkniko** [comment]
Look for saves in here or in reddit there are some ... with DM .. make saves periodically

**Comment by athayward** [comment]
OK will do, thanks
