### ISSUE TITLE
IRS and Alcubierre Drive costs issue

### ISSUE THREAD

**Issue by httpnet** [sparticle999/SpaceCompany#311]
Interstellar Radar Scanner and Alcubierre Drive are the 1st cost at the time of a load.
When making them read the following cord, a problem is corrected, but I don't know where to apply patch.

Game.interstellar.comms.updateCost('IRS');
Game.interstellar.antimatter.updateCost('drive');

**Comment by Unihedro** [comment]
Still persists

After buying a new drive:

![image](https://user-images.githubusercontent.com/5595067/50513781-cbcc0200-0ad4-11e9-9530-75c8c31332be.png)

After reloading:

![image](https://user-images.githubusercontent.com/5595067/50513800-e2725900-0ad4-11e9-9ce5-9f44d90e1623.png)

**Comment by sparticle999** [comment]
Hey there,
This is a known bug and it is fixed in V1. There will be a stable test version soon released on the space company subreddit. Probably early January
