### ISSUE TITLE
Uranium not reducing

### ISSUE THREAD

**Issue by galaxystef** [sparticle999/SpaceCompany#32]
Just noticed that the Uranium deposit is not reducing when it has a negative production value. It just stays fixed on the max value

![image](https://cloud.githubusercontent.com/assets/27204481/24860490/8524f548-1dfd-11e7-9d1a-c2c815cff7f0.png)

**Comment by sparticle999** [comment]
is this still the case? have you saved and refreshed the page recently? if so, can you send me what appears on the console (Ctrl+Shift+J). Thanks for your help
