### ISSUE TITLE
Charcoal Tier 3 - Industrial Kiln error

### ISSUE THREAD

**Issue by galaxystef** [sparticle999/SpaceCompany#33]
**Get Kiln** button does not work,  getKiln() function is not defined

> (index):1022 Uncaught ReferenceError: getKiln is not defined
>     at HTMLButtonElement.onclick ((index):1022)
> onclick	@	(index):1022

P.S. Take a look at the last comment in this too #28

**Comment by sparticle999** [comment]
Thanks for this galaxystef! I must have missed it somehow, but it's fixed now.
