### ISSUE TITLE
EMC Plasma-Meteorite

### ISSUE THREAD

**Issue by kaweepatinn1** [sparticle999/SpaceCompany#339]
Cannot convert when plasma is, or is below 10000. So have to manually change to 1k and then 100. Please fix.

**Comment by sparticle999** [comment]
This is intended to prevent meteorite production deficiency on low plasma. Reducing plasma to zero turns meteorite production to zero for a couple seconds before starting up again. You are able to use all the plasma if needed through these manual exchanges. 

Sparticle999

**Comment by RobLeachman** [comment]
I logged in to report this issue then realized it was already here as EMC :) I agree with the OP, changing the units is tedious and since I'm now only focused on building segments I wish one-click was sufficient to trade all available plasma for meteorite. Thanks!
