### ISSUE TITLE
Discord Link

### ISSUE THREAD

**Issue by pyrox0** [sparticle999/SpaceCompany#346]
I have already tried clearing my cache, but the discord link does not work. If this could be fixed, that would be great!

**Comment by sparticle999** [comment]
I think I changed the link. Are you sure? Try refreshing again. If not, it’s accessible in the subreddit in the sidebar

**Comment by pyrox0** [comment]
I have tried the one on the subreddit, and it has worked. I have joined, and I will change my nickname so that it is easier to identify me. My profile picture is the same on both accounts.
