### ISSUE TITLE
All game data erased and save not working

### ISSUE THREAD

**Issue by AgentFred104** [sparticle999/SpaceCompany#348]
So, I've been playing SC for a long time, and have a bunch of dark matter (something like 6+ rebirths), and I keep the save stored safely at all times and update it every day. I had to restart my computer, and when I went to import my save, some of the data was erased. I have access to all the solar system resources, and every research type I'd been working on, but every resource type was set to 0/minimum storage. I'm also unable to buy anything or gain any resources at all. I can provide the save if needed.

**Comment by sparticle999** [comment]
Did you get it to work?
