### ISSUE TITLE
Storage Upgrade Dark Matter

### ISSUE THREAD

**Issue by kaweepatinn1** [sparticle999/SpaceCompany#350]
![no research yes storage upgrades](https://user-images.githubusercontent.com/37656629/39796291-450869a6-5388-11e8-9a0f-d27fc667e7ed.JPG)
I have no research but i have storage upgrades. Is this because I got it before and dark matter does not reset it? Thanks.

**Comment by kaweepatinn1** [comment]
Oh yeah, also I can destroy the machines without research.

**Comment by sparticle999** [comment]
Hey there. Dm upgrades are carried forwards, but storage spaces should not.
