### ISSUE TITLE
Meteorite Tier 1 & 2

### ISSUE THREAD

**Issue by darkniko** [sparticle999/SpaceCompany#354]
I started to play again and i noticed something that maybe it should be changed. Or not .. 
As it can be seen Meteorite Tiers 1 & 2 cost the same. 75k each ... According to everything and anything in the game each level u buy of ... anything .. the next levels costs much more than the last one bought .. So idk .. 

![met1](https://user-images.githubusercontent.com/24360651/40852783-117da8fe-65a2-11e8-9193-9b462567744c.jpg)
![met2](https://user-images.githubusercontent.com/24360651/40852784-11a40152-65a2-11e8-8219-14e38a637236.jpg)

**Comment by darkniko** [comment]
Made rebirth again and noticed the tier 2 asks for 75k but actually it need 100k science to become white available. So it seems its only a visual error.

**Comment by migue1s** [comment]
You’re right darkniko! Thanks for the report :)

**Comment by sparticle999** [comment]
Fixed in V1.0 :tm:
