### ISSUE TITLE
Hide Buttons

### ISSUE THREAD

**Issue by darkniko** [sparticle999/SpaceCompany#355]
Many times i had the issue where i missclicked the ring button when im trying to build a swarm or even worst clicking on swarm or ring when im building sphere. Is there a way to Hide the Ring and Swarm buttons temporarily? Like a Hide /Show button for both of them?

**Comment by sparticle999** [comment]
There isn’t currently but I’ll put it on my list for features to be added when I restart development again. I’m on the brink of my exams finishing. Just two weeks to go!

**Comment by darkniko** [comment]
Dont worry about the game. It can wait. Study, studying is the only thing that will open new doors in your life, not only work offers but many others too.
