### ISSUE TITLE
Get Tier 1 rocket button does nothing

### ISSUE THREAD

**Issue by aadonald55** [sparticle999/SpaceCompany#386]
ok, i have messed with the save file, so i know the overall reason it isnt working, but i was hoping you might be able to help me understand why it wont work.  I can share my save file if it helps. Thanks (I like to deconstruct games and see how they work just for fun, and your game is so complex that i always find something new and interesting) :)

**Comment by kaweepatinn1** [comment]
getting a tier 1 rocket doesn't actually do anything, it just enables you to travel after unlocking communications and getting anti-matter
