### ISSUE TITLE
Solar system tabs don't collapse properly

### ISSUE THREAD

**Issue by Kiblinix** [sparticle999/SpaceCompany#39]
The inner and outer solar system tabs don't collapse at all if you have already selected an item in that section such as the moon. Seems to be because the `activeSolarTab()` function removes the `inner` css class, and the collapse method searches for objects that have that class and doesn't find any.

**Comment by Kiblinix** [comment]
The same seems to be happening with the resources tabs too

**Comment by sparticle999** [comment]
I've fixed this. Thanks for reporting it
