### ISSUE TITLE
Machine Layout Idea

### ISSUE THREAD

**Issue by alexanderzeillinger** [sparticle999/SpaceCompany#390]
I find this table structure with icons a lot more readable. Anyone agree? 👍 

![image](https://user-images.githubusercontent.com/126621/51056667-b205e100-15e3-11e9-843f-625bc51e2582.png)

**Comment by sparticle999** [comment]
Hey there, this is already in the V1 test version. Here is what it currently looks like: https://imgur.com/a/Ag5hyBf

**Comment by alexanderzeillinger** [comment]
Great!
