### ISSUE TITLE
Incorrect Total Fleet Attributes in Military

### ISSUE THREAD

**Issue by kaweepatinn1** [sparticle999/SpaceCompany#392]
![image](https://user-images.githubusercontent.com/37656629/57221999-ac6d5480-7033-11e9-9ada-2899ede0a07b.png)
 
Also, do faction star systems' production carry on to next resets? Otherwise it would be a waste of reputation. Thanks! I love this game...

**Comment by kaweepatinn1** [comment]
Also, try to add more star systems!

**Comment by sparticle999** [comment]
They do not, but as you are no longer oppressing that planet you get your reputation back
