### ISSUE TITLE
Uranium is blank

### ISSUE THREAD

**Issue by MasterAries7** [sparticle999/SpaceCompany#42]
I activated the wonder, and Uranium appeared on my resource list, but I click it and get a blank screen, no way to upgrade it or buy producers.

(also mine still says Space Company v.0.3.5, even though your changelog says 0.4.0 is out.)

**Comment by sparticle999** [comment]
The page might be below the resource list. This sometimes happens with smaller screens. Also, the game is technically 0.3.5, but I have added some of the 0.4.0 features. The ones in the changelog are added, but I haven't finished it, so I didn't update the version

**Comment by MasterAries7** [comment]
Yep it is below the resource list.  Didnt think to look down there.  TY.

**Comment by sparticle999** [comment]
No problem!
