### ISSUE TITLE
Text issue

### ISSUE THREAD

**Issue by insberr** [sparticle999/SpaceCompany#425]
It’s not major, but the way the text is really annoys me
Here is a screenshot of the issue (from iPhone)
![A201AFCD-1279-4986-81C7-25F48DB3300A](https://user-images.githubusercontent.com/57020076/73238341-8782b980-414d-11ea-92dc-b7bf749ae1aa.png)

**Comment by insberr** [comment]
Here is another example 
![D15E2880-912C-4906-9BAB-ABB82894BD3D](https://user-images.githubusercontent.com/57020076/73239045-d92c4380-414f-11ea-8790-707a7506327c.jpeg)

**Comment by sparticle999** [comment]
Unfortunately, I’m not building the game for mobile support right now, sorry

**Comment by insberr** [comment]
Ok, that’s fine. Thanks for the great game you have created!
