### ISSUE TITLE
Annoying extra space

### ISSUE THREAD

**Issue by insberr** [sparticle999/SpaceCompany#426]
There is this annoying extra space on the achievements. 

![98F26A6F-DD5F-4C92-8C0A-477904E5EC26](https://user-images.githubusercontent.com/57020076/73238985-b4d06700-414f-11ea-8228-1b7121d86c8d.jpeg)

Hey, thanks for making an awesome game!

**Comment by sparticle999** [comment]
Those are intended to separate the different sections of the achievements tab. In V1 there will be another miscellaneous category

**Comment by insberr** [comment]
Good to know. Thanks!
