### ISSUE TITLE
Meteorite Production On/Off

### ISSUE THREAD

**Issue by bd5872** [sparticle999/SpaceCompany#47]
When meteorite production is turned off, the plasma stops being used, but the meteorite production carries on, without costing plasma.

Example:
1 x Super-heater, 1 x Meteorite Printer

Meteorite production on: -2 plasma/sec, +1 meteorite/sec

Meteorite production off: +1 plasma/sec, +1 meteorite/sec

**Comment by sparticle999** [comment]
Thanks for reporting this: It's fixed now.
