### ISSUE TITLE
No rocket fuel

### ISSUE THREAD

**Issue by demonindenim** [sparticle999/SpaceCompany#65]
I have 25 chemical plants but I'm not producing any rocket fuel anymore even though my chemical plants are on. I just randomly stopped gaining rocket fuel. I also refreshed my tab then reset my computer and still nothing.

**Comment by sparticle999** [comment]
Is your oil/charcoal empty?

**Comment by sparticle999** [comment]
This issue is being closed because of inactivity. If the issue still persists, create a new one.
