### ISSUE TITLE
charcoal producers don't consume wood?

### ISSUE THREAD

**Issue by fpvandoorn** [sparticle999/SpaceCompany#66]
My wood income is displayed as 12/sec, and that is also what I get from calculating from my income from wood/charcoal production:
`74*14+12*10+100-90*2-0*12-19*56=12`

However, I get roughly 1k wood a turn, as if the charcoal producers don't consume wood. None of energy/charcoal/wood is close to either 0 or max capacity. (playing `v0.4.3 Beta`)

**Comment by sparticle999** [comment]
I'll look into this. Thanks!

**Comment by sparticle999** [comment]
ok, I think I fixed it. Does it work on your end?

**Comment by fpvandoorn** [comment]
Yes, it's fixed now.

Very nice game, btw!
