### ISSUE TITLE
Per second numbers aren't changing on resources other than Energy/Plasma

### ISSUE THREAD

**Issue by slackermom** [sparticle999/SpaceCompany#71]
This just started today when I opened the game. Here's an example: Uranium is 101/sec but then I buy a Nuclear Power Station which should decrease uranium production to 94/sec but it doesn't change. This was true for Methane, Helium and Hydrogen. Energy production increases however, so it's like a cheat. But now I'm afraid that I've increased my energy production too much and when this is fixed, it'll run my resources down to zero ... although at least I can destroy the energy producing items and bring things back in balance.

Let me know if you need other information. Thanks! Love the game!

**Comment by sparticle999** [comment]
Is this still the case? We did some bugfixes and your issue may have been solved while trying to fix another.

**Comment by slackermom** [comment]
I noticed that it was fixed when I checked it this morning. Thanks!

**Comment by sparticle999** [comment]
No problem!
