### ISSUE TITLE
Purchasing

### ISSUE THREAD

**Issue by salucarelli** [sparticle999/SpaceCompany#87]
I am unable to purchase anything under the "Solar System" tab. I can turn the fuel on and off; however I am unable to actually build any chemical plants or even build the rocket itself.

**Comment by sparticle999** [comment]
do you have enough resources? If yes, can you send a save file? I'll take a look for you

**Comment by salucarelli** [comment]
Plenty of resources. Here is the save code: N4IgbgpgTgzglgewHYDkCuBbARtEAuEABgDoAWYgZhABoQAHAGwEMYMn9DaALCJgF1x5OIHv2gBlOkwDGEALIQ+TBgGEEMPvgDsAVkL7uvAVADiEDGo34AbAA59w0cfFwGcackua8OgJwPDMSgAFQQAczCGCAATfD4oNAhaRhY2PncOZOZWfndJGXlFZS98WwBGB2EUnPTpFzcPJBK8LQAmSqzU3OkFAQQoOAFm3y0q7LT3UIio2Lx4xNoIJGgwgE8bdtItMlJWvX0yrVJbWix+Y3WhU/PoVd7i9W99gxAzvguzC0f8Z+E3i/ysnuqm+eAoHVeNygq2CrUykPet1hwOaOl+10R0Nhn1R6IRF1hgMKShBVjB4ICIGkXCYUA8ygAokgwnBljYTlSaXSEIzmaziQ8yRRWtYKKRaNTafSGEyWcscaCyqLDhKudLZfyAPJoPh0HX4cUgGAIZhQAAKTGWDG0wmNpotVpRoNaFGsvlatDttIdEAYCrJrS01lIZU9Ju9lt92t1+rBtAwihpy3ESnSyHhCb4SYgKdyyCJTrJZQq8cTkdzaaQwUGlrgmGGwiQaGkUVpFcQSHhTZbvCg7fzUiBRVJ3nalO7rb7qY71aUSDrXyLELYYQm0gzTFX3QLw+ae0pK7X/tHy83a/qkCgzTKz1oADM0PBkAAlXjSPj9eEPp9IV8yD99oOAojvgFIvN+HZ/u+/SzrW9bOhCEEvm+AH1O4niKreIAIK4oG6K6rTEIQ/jWM81jWLQOEMCm/SbhABrEdYLxUSgEAAB58DRUB0aUZTui8eoYHQNrJJgdCFt4WwULYhqCXQx74DeWi+LJYkAFYyAA1opVTqVpEk2McolCRp0iaQpeCtO0xl0KZmmaq416tL4Nl2dGereCW2GuAAYnAvqzMIVF+QFO4knupDMb5/kMNEsHzvBAajEF0Wha46FNKCFD+ClDDPnAYTwlR+VhGFgqeSpUV5QV8ULtedhVSVvQQP0gwQM0QbCJmyiKbYrR9cQZQhs5vijaNWhaKWJJcTxeBKtJkVdcOrEcTNYT0WCgYNV1/JQPg/jxrtBk+BQZTgodyxQAA6ggCDRHupGkYEYCrAAIgMDDWj4k0iLwL3va4DDHa6TGhr9TD/R9frmNeFBtDoz1vVDDkgXNQ3SYjAOfe5sZKrQLJhEwWNfcIBNE1DZWo/1Lxk8TFlijTBXk4DaGNM0IYvAAjmglp8JgxPwtzvP8xTQHHc5lJC0gfMYHTJr3YqtjJbQUsy8TzWtUMoI5fj5j4Js9ik+Ya0bQbNPmCtnEAbNkW+ExRsYHIu0iSA62O0du6KmUMkUa75hO5dFlaLYIy0Ew0RgJasjRALeCkL74eR0g0fq57ZJ260YOJ1HMR0zDipMRQCMgNnye58jjmgscXmlynyM6h5pS0NEcBMBgyAx1D8It23HfE5TzQM8IPft0gneAxZhvD63o/j59rMYWSpD7BKtJYKsyyx8I0hrxvED92LaejhULw71A6+b1DFmBpSZ8X/vUMawMWtkobqpSjyX0usRStEYcSqjUirod+3JlAmwYnbU+apP6W3AXgco/Ft7QOUFMSIMQ4gJCSCAAA7rdaIWA0BQEuopWguC7oEKIdAY6xZSF4IoZdG6d1UT3kIUgAo+ti4PiIQUY6thyIsO4bIRhCsl4UAoAIthsgUbXkILYcRIAuGSIgMIgAkkgRuc0PQKNYQUHG3gOSaVcJ2K4IBDEMCQAPLKK9TFGIstYMctAzEWPSmzLKb8FHQkEMIO8njAI8KPopHQ7ifGrGgAAGQhkwJy1iQlUMUC1Z+7VQQ6CYrQu6BpSDZUzsQNE7oxpaDKFosh0Q4EIIcTgvBsDrbrUUqKGSLxinSB1MYbQxdGnNLieFRUgZvZpOiE0zEwjmiij8LQbI0AVAdL2nHYQ4yrxTPFiKLRczJmYgskA+RKypnSMVl5LZmI9GKS0dECAd5+gQA0F45upzzmXL8UOLpQpKQnLOVAC5xhaqJVHMrEALzbnOBcYvUc1jWTfiuSAUFj4JCH0eZ5e2whIUwGgDsoUhSXiIs6Qktq7MDpGmkP5MuBolJBjIMHKeT0QDMCwD8WZTAsBDK9loTZdKLKHFSZSul4sxQ/SpbCDhYy6WwgZWSHQIYeWCtaNfJUvteWtGobIsUAqsDBCoC0JVKrhWeSVoQcVyqKAWV8DeDkvKKDA1Ov1WgUAEBmUUPCK1Nq+A+USCTS11rNKKCdb6VBMx8B3mUEi1U5h3DKDNMwaW8JqRBp3gwUNvN5VQKjSGsNfAg56EDRgYNMbk0oqeMxNicAW4wDzMYoK+bC3FuoWOUtBa4BFsrJPCklEy21uLTm9kLwYAwp6iYzt/jprVI2mmo0XaGBVNojUuaLxMzZgzGWZMA6aVTWzGO7iE6T60HSHOBc8JN1wQwHAodu6EoYBXbNddrt5bwjCPLA9pN5anrXR21wl54TwAYJeW9npn3QAfRtc9b6MqvsBRYhdPhbTAd/TpLqt0kA3SgO66Z0HkBwYQxZax7dkBb3jDB1OsKoNIaQHnRc3h7bYcwxXVGi0yNIAAIo8ygNCDMMG6O0mhJY1+B5mP0ehGhzjyAWMMdWAvTKQprEpGWHwBkbEd6RwAvCcTigpMyf4DBGsx72ZYQU5J6TkSAIqNkIPZKYxIzaeUwBJ+2LkkvEjk0zA8IbNoEwOx3NtAHOYF47aZslYlO6c/D2rzHYfOyf6M5qDnoAvICCyp0w+cOOeffIFnTwWoBtrwKR4dBQ1DYNfUBLLoXJ2Ul7QZhA2DPnEf2oV3LJXhPs3PZAcNJj6ucRHaiKtrmlh8AABK+jqlXIz7XpYWZft4bKwh2KMHOYhxYbEJtvJi+VgrtoR1YYyw85QB8+3lX1h25bV9Yv6J25thgxNUsnyqB15mn15MXY22t1GQ1KR0Bu3thbxZHvPZZsB1E6Wj0rd+6LI7wywIbrU3LWKe5+sgH+4DIbSSyTpeiFagt3ckclJawhYeqPejZlRMPd5VrQlTd+fjhAhP8vWJORoAn0BWUU5J4T07zyjBcFzETk5/AWdKHucBa8kP2dZlZxeCZXs6cc8F190EfUXj/h5nJkxMvov5esGdsO75Zf9G624L5gSfkK/M/EzWcOSMdo8LGW0pvmuA8VCbhAOoyt7iWwUCJSKidFYgM76FVvROO9kB7+bDYffu5YMiyuRZyk4CgFmdgJiI9R/y3xaxseaT28VuH6AceJdFhV1SS0SB0wmJ3kgPPFj0evx0OewvxfUu+GkqfXPyBYetb+AwErAFqTwiwC37BbeWel88kOzvrf+jUhT08z0Hg6Q8FdxPyN3PjrWJgDPqfrLymL+H1P076Xc9wC4K4aL8Jt+7+YKhPvoFKSH73wBBt0ui878vyF79V5nRUeJy77weO3/5arR/9PNXFQTReEp3T0byrheDeSRSlC4AAFUkAW8bVZh5gsFwDexI1ZgABtEANAWAt1cBWgLAuA+yXCPA7AsyAAIRYHcCZBWHWGIIIPEHDD2loLdTkBkF32WBgBoEwLoDCG4hOVfGNEIVkGCAgHbyYLMlenxwi07DwO4N4IgA1GWGENEMwJIM0noNNHEFWEuQwE4PwLdQiWVThBkJ4PDhzAYKUK4F0NUOfDdQ9WdT5TEM0gMJVSsIIPIMxH8g4IAF0w5I499O8NoMC9CzJcCVC3CKDpAqCoA1hXC3UUZYiQiGCEjNIWDqR+QODjC5CFCIALDdDZDTD1DaRcjHDCi+wtCBAdDMjTD+Dbc6QciRDLDHCJCqcpDkjnCjCwi3UbCHVPUGAHDOizJnCqBHD3DjBPDkjRjoBPC+UfCoc6UYAYCCD0E8AMDkDIDgg6VOCvQyjtCNjqVZjwDajZAFjVDliMCWIIZOClhqCUBLiQFpRbiwBOD7V3VHV7COj/gpiLkrjLo1gTZSCEA2IQBZi88ASoATlpk0CDjbC+AIksDUDfV/UsEBBqRFjbDZg/UGAA0QBMwsUBA0T4DESsSsECF3hkAYBOsC0TljEoTptZszjZjCE914QmTj1P1MDuJj1IMCtVd0hZMGT8YBgx5wUeDWQITR8TwaYhSIT8tFpSZpSad5YHdT40AsAMgC9VT3AoDOTesOMJRNS6hT9Ftt4DTGdKQlgBhZ94QLT3Ap8v9DgXgbTZ8JT9ZgcQAnS7TM9PIi4wCRDVgewic3lpB/Sog58Ak8Aa9z0gyQzOkcc+tKRoyAyQDX5zoOVI54RmBI52TMymBuSK8Eh8UAiI0Cy4AAjZTb4SyAjJ5zSOJuJoIid2J4h/wQsjSlQaymz6yXTNF2y6zUIvSbAey0AITrTayhzPc7thkcoxtRzxS1NdSnhIdGyEgZT+ywQpz2sGA0A6A+Z99GtfQtydyT8vdRxfAp4NyDz1dTAlTuls9IBNztzLzkzvBdBHBVhEdwglh4QuA3yrV1oQNx1B1Xz3y/y8zT4TQoh6yI1wKRCjyJzQR4UJRoLOy5ztc453EVwJMNwwgJN49ZEp1NwJMuzIEuoCLFATBrz4d0t2pfQXV3SVAaKhcn8hQ2hHT6LPpyLwcspdhWKGLVy9h3E2DqSKFCoTFBKlhhL48WKXgxKkBhLsdIxYY5TuAxTxLCEwgnztAvIeAtcdDRKesnNQMh1tKFxQLMdkANozLkwjT6lLKcxVyEK5ikAEMd1LQEN48RQXg5wEMuyKhykvKJBVybLEKhJwDjQicPAQqLkwqlc3SIq6BQrVMt1ULMl3E4qEq+xVyi4X8YBDEMAExXdcr8qv80RCtCroAfKmVSq4A8rMVDcOpRhaB3ALLGrZB2SmrTKWqIAzR3BtITEmruqQjWzg50VZABrzJ9tFIa8RqH5AZ4QmrbsednRRsEVZBiYuzM5yl5qKZVy+J0sfEIAIAAAvcFfao68cxarPSHU646kIFChbPhSka6gKhoIFbQN0jAKAHyN5M6jMT67646zVPCdcnEv6g646zXecxSJSkGr6sG4kPEo3QJKdA3RJWdPoRJdk3Ew3DqnElGtqb1ZYxA5IIUlpExeK1kZwVsyoKoEm56jKXHSkbBCAalExJmrAfLKaxm5m7UvdHFCENmv/EVM7YeLQ/PEW40KsO6weam5uUWpADikRTyGW35OWwWyU55OWjSxbWWiW/TRG40pbKfZqo0bBWkXS4QIUkS4QVg/ySABMaWDgvAUAS8H8A0RYaWAYb4p2kuakAAfUIFAlVy4F9rKH1iDt9rhEsnDtVS0VYN9tIDDp9uDp0ETrju9hISTpDt8AzrjsDAPz9vBBzoLtDvlwLoTrmmjpTorszukiLuDuynzuDt2DrvjtVWtr9r4RbqVg4AAF8e7PRpwNB3BHbnboBXbq6OtPaR6cTLQeY8oLkjivbnb9Z7FXNo8ll+6od/IUtsFlhogS7l7LILVwB17+pN70hkVd6YhI7D7iwwZ0y0Yyhz75iCT3VZhD7i4H6dBN7DjBCLlX7ljD7fYH7rBz6Gj+CUCeB37wBFJ77o9ixN6kUYAfxqwEx8BD69hdBiAmJSIxQhp7YdB5EH7MGdBsHCBcGQx459BCHz7qqurmBQloGnjLIdAsGcHCHKGCGiH17WHSH2G8GqHCAaH7x+g0hSajQuB+g+Bbi0HTh5YmQ6UfU8BMTsT4ATkzgn9IrkHliVHkSeA0GCAzgkVOCmAdQEBxAIYIA1FjBI4vowJCA+7LUF6/7p7mHi5plQBrjojLhQAS08CiSkVN7qg2B0GQA/HMCAmIBN7WTt1vbwm0BInN6czQn4nEnKJcI4mWS0ncaSQUmsm5hMFN63Y8mTEEmCnEhN7JRQEvpfH8ndHN7ikSnhAynEDEHgMmn/HlGkTEGR0OmImuniTN7p1Iw+myn6mQckrdLanSnsnr1YpRnsm30X1MmZmBnAnuAfyPzjFpnmnsnjK7MVndm1monOqFnjmhm8aBAznxm8UCVZBrnunHHXg0BXAW5mRXGM64BQmvG1hggS6xtfiYRI6AXqCXCTEfmYRy6QXvHggq7oXfnrB5NxgmA/mkWug+VSmdTMBUXMW90MXmmsWMAwWCW8WoWBVI4cXaUKXgXyWUW27aXggyXvI+j/n0m+iaXmXiW2XGW0aUFWWcmUEOXuo+j6WBW+imW3ZKXdYiWOXJXRXJWmWqnpQpXOQP5BWI1kERWNW1XxX4RikVX9WOX9XRX9WmWANGgVXzXkB8Wv0XqqxRWrWqwzWR1LWXWOW3dgQuXVtgIeWTFhnFD+X/WcihW50cjRWg3fXhAj0FwVXo3sWOW42iXRXE3I38Z5YVW5m4pZX035X02zXH9LWC33WC2HWC2mXvzgKlgVWK3fyq2OWa2tmvWG2/zU3fodLq39KZWvzO2m2e2mWmqVWB2OWB3RWB2mWsbEkVWJ38b3X8UlghD+XF87ng3X052y4vWXi7CvV+XN23ivVgWnmUTLDvbmGwYvnvaNAAKoD8iTlY0chX0B1r2TCTkebj0H2r2b2g8H7bRH3P34ie1f3n3gJ33V0IAn25DPgQO6JwPTCVBNWoP1oYOTlhEEOwPP3hNUOkOcxemAOP2gP5K2RcPQOsOytMPP2FayOgPGLKO5DOtNm/yaPTCIaDmf28O5C9bGOTlYcWTVDyD4BIjAWeOCCUYzR7UorWQraSikjSnrDnG6jUi2CvbmnVDmj5gEsxapONDyi9YZOCD2ihP9CmA6AvXgjNJJisR+XTPzOgWDOzI722AVXTP7OUWOXTOGQMB1xdPmDLmcjLPVDYcbWBiUifOTOVPVbTaoBzamjVa6AjaWTP2ai/7cjSnP3sjkvmn0PzCGjrS7w7x3A7nVgIHIDFInmkV3gJPXGx6OwM7J7xina+6e6gA===

**Comment by sparticle999** [comment]
thanks. I'll take a look

**Comment by sparticle999** [comment]
looks fine to me: 
![image](https://cloud.githubusercontent.com/assets/9462415/26760975/142a522e-491e-11e7-9e6a-b0b0938f0aae.png)

**Comment by salucarelli** [comment]
Strange, I still can't. I attached a video. I even tried playing it on multiple other websites besides Kongregate and the same result happens.

[Space Company-mp4.zip](https://github.com/sparticle999/SpaceCompany/files/1050459/Space.Company-mp4.zip)

**Comment by sparticle999** [comment]
[ice_video_20170604-202423.zip](https://github.com/sparticle999/SpaceCompany/files/1050638/ice_video_20170604-202423.zip)

**Comment by salucarelli** [comment]
Well crap. No sure how to resolve it then. I appreciate the help, and I enjoyed what I was able to access of the game. Keep up the good work.

**Comment by sparticle999** [comment]
If worst comes to worst, try hard resetting? This may fix the bug and it's not like you were going to play further

Alex

**Comment by lejonmanen** [comment]
@salucarelli Some things you can try:
- open the "Developer Console" by pressing F12. You should see a new window in the lower part of the browser, that displays some messages from the game. Check if there's any red text there; that's my best guess

- are any other buttons "stuck"?

- try another browser, Firefox for example

- check if you have any browser plugins that may interfere

**Comment by User670** [comment]
Uncaught ReferenceError: getRocket is not defined (index):3464
Uncaught ReferenceError: getChemicalPlant is not defined (index):3406
Uncaught ReferenceError: launchRocket is not defined
