### ISSUE TITLE
Meteorite amount error

### ISSUE THREAD

**Issue by jwyt14** [sparticle999/SpaceCompany#88]
I currently have 50/50 meteorites produced but the game doesn't detect that it is full, either on the sidebar (not green) or in the upgrade storage area (still red).

**Comment by jwyt14** [comment]
Save code:

N4IgbgpgTgzglgewHYDkCuBbARtEAuEABgDoAWYgZhABoQAHAGwEMYMn9SAmANgE5jCAdgCsI3uIAcgiqVoALCEwAuuPAEZ5ilVADKdJgGMIAWQhKmDAMIIYS/BM7DChTcugBxCBmu38g0hLOrto6cAxwBsg+dnjcpLxBIApuUAAqCADmGQwQACb4SlBoELSMLGxKEfgu9MysyhF6hiZmFtH2as6JZfWVBqHhkUjteIKcXTU9FRGmKghQcCojvIKTddMG6Vk5+XiFxbQQSNAZAJ74nBTcosKUwhQTnI7ctFjK2ud4siBvSh+zbRsMWk42Er3e0FOnm8QL8FFB4L+kKaRgBVlhXwovEuiI+qU41VxkPxaJGwicXSJUFO+OhZIpiV+eM4KJa5nRvjwFAelJABjkTCgkQsAFEkBk4Md8A9aPzBcKGGKJcdSRjQYJZQKhQhReLJRA6RjOpwJJr5TrFXrjgB5NBKOh2ji0GAIZhQAAKTGODHw3A1IBdbs93tVnLUgkCNUDguDEAYhs540EfudrpjXrjtvtjq5tAwZgFxx05kqyHwTjzBYzxYayFZoZiak4vCblaUhYgNdLSFSiy9cEwI06wmutCQaAMOUFXcQSHwag0IHHk8UuhLs/rrQ5MVEhG4nDHE6na9rPb7SAHMMTEnui7YGQ2fjzTAfDX6+lRW5GAUE4efr76BMdwkUhuDvF8NgGSAoBGCgJBWb4ADM0HgZAACVFAMJR5guWhkNQpAMMMbDdA/NlAU5K4eTwlDZyIrD5l7cwL0HNUuESfC6MwkiBgiKIjQkNQKxABAwmlFsZG4Yh9wCYRxDA7laFEhhi3mF8IA6bFEmUlAIAADyUVSoHU+duDg0hukwOh51KKyG19F56CsoCLgPJyMDoAArQwAGtCXcrzfPs9Rrm4RyHQ87yDB8ly8BHeFbMi3zrTCWCKDUChEsC6KswdRsamUgAxOA412RyipKhhck3dlv0cRcKtKpj+1YzlSAjTKRLCYrSt4oYRj4QheCUsI0LgDJ/OUsaMhqijG14CyCtG8bmpYq9G24SMRoYabZggeZFggEZkxqfN2T8NQ/QkKTLjM7guhkNsLCMky8EErTTq3XSDJejINJC8zEgwfUoCfEBgeOKBgrUYbwZBgB1BAEFyZZXDAU4ABEFgYH08HGNHMexhhguEUgLIJrGwnjLwRnGcmkkUdHKZxlLt3nVYamSJmidynNLtoCUMiYZncc6wXhaJ2a2a5MZHPFkXYtIYRHAF8aJapvr+M5UnRFoABHNAvSUTARf8g2jZNyWyOC5teXNpBjYwBXXRRgSOf1w2Hctqm9oOpYMQSGo/owecuBHCRKFA3g5Mkb5g9+/7LsBoOvG+wySNe+Fky2kBg+MEH5xTjB88h4K4IFrwS48Gm1TBEAmFyMAvSMXJTfUOuG6bpAW5F6HLq4WhO+bvIFZrsMFsITqh+7keedSjFhAcRdp57nm7Ty+xaFyOAmAwZBW6Jp0QG33f95FqXvxWf0T73pAD6p2KF1/Nyb7PyWwj44YMWuCRTT5QUsCnGOG3GoBgAFAIgOfa2X41SdESGAqAgDgFE1ipwDmoDwHIJ9mYfaCx/achznKbUFgLjRxAsQXg6UY7iEEC2M0xCVIZz+oXTgi16EKjTgnC4hAAjwK1AqLY2Q8gFCKCUEAAB3JGuQsBoCgJDfykjkYyLkdAPutBFHSNkZDRGyMyQ0Tkc0aUblkIGM/LVASi99FIGaDo12nJsSwxMdYowrNabwmMVomxUiACSSAN7qA8aYiAvMYh/x8mEOceAajhIYEgC+GIKAUloDEpAsV9yJBSZrL+lEc6IWpKoGoeTTjQHiWGReHF8lQAADJMCbkORwFTilQxwX7I6C97rqKkdKa49xiByXavdQgSZHIaK4eoIZbCJFSM4Uw/6dMc4aIMHabQ85FyLOWaomB15OnIyWUiKAtihzfDqNASwGzQZcmOSwU55zoZoP9CcmC5zUHNlho8s5+zXFGiGYud55yQnzhfhARC8wIC2AKVvYFoLwWkWaGXXkuQoVQDBdoVal5abu2PkilFJSP79VrokSU+EIUgCJShEp0DzFhkGTUMlMBoBfMok2QlSBiXNLmHgtpbUEjOgMCVGepCxjtUoGghkrDHogGYFgaUnUpWHLVAlSVTAsCxRkH/KVwVQJXKwPiQFtApX4nlWUvg+rlW0jHjEfcDyzWcDLhldVZqqDqG1akCgRqYhXCVnXA1FBH4RgCKanVFBgpxHJP6KACBopmH8hGqNShCrFFxpdTgagI6EDku9eSC5Fyxp8mYBNcZBE7BEQcPkChgZgIYO6ZgDt/L8i8BECw1ajZ9z4Q2ytzaHaxQcHXetFam01qUIyncwkEB6TgNvGAp5cIiXHZO080Mlb41nROuAU7uyP2cKQTqY7V3rtnMO+wTw/4wEpSQ8ZEYRwCD4IHLoJ6z2MLUswvGPCc6nrhV9fS6cn3/QsrwQZbYOyApzmdDsYymwgarMcGZP6LgjkSJUZil5pQ8MuCQbdghaHiCVn/RDLUMBjL/QBkAeG1oweMs+964wg4u1DtHTgZAeAgQmDDf0GQXbgYmYkdjVVyOvXmYkeADBoLcN4VGMI0ExkCfE8J6AfHn1EcE3isseMuDpWkuIRJ4hJC6wDMpuJsyOBDWI0Jz+8n/pUaBkjJAiMoB5ouRlPM1nbP2b9TwJzyAQEeaQL3LZ80YbfD3p5lBFrVnCH5uDazItD2jD9P6ILSAACKhsoDUnnJ1BLyXBTUlKTENBYE/6ZZS9SNzYFvNZdS6cLJ9TCAOFKDWswIo9JgKbiRfyZRjhKCay15QjFzzooxErXkHXGvNdqb1qA3ijCwXQfVjMXWxutfmL7TlZJEhNyWZgecdcNtoEwLl7hf9duYFQbVk9E5uzdfG21vG52sKziu0t2FZi5oXGzc6C7D3FsTcfptOhAZPvIEexNmLTYwr3uaNYcRM733TYQOIg7eMEjfFh208RaLWoep4P6VHUPquDd/LDSAtaom0GJ4ZB9ZJqM1HJwACTjANtqs3wBHCUCtw6sEeUgH0owUFFy/484YHz1Baht3OgfW3CLqO0RQI/VSmILYIcvYYKPda3SRDi7lxYaL882r9NKKz9WOMbL0EN7L5XQ5SbdDNyFtXAS4EG4dkblS+mBqXRqKRrzJHzzm/ItLMyvJPcoJdhiwPPuibs/wZaxIuQI0TpnbH0S1VKdsRfnH3IswOwDRqIi2wEamnSkhXnhATTEdhTrrnwoJfq525hv+ovVemmg+5IuRFyg5A1guTnrQHfzDPb90OZnbf2yd6gqco0QkY899H67jEDhEjEUNjdmoi+Jtl7gSvrCS/5j0/CJj7bmLV8kUj1y6PUZIg5jcjAC/FOtfSybIua/CA7QY7t6wzXRgan0q7x/iAX+KV35kitgBhkT/5QCPzpQ46gHXJQCg4iCOQ4BQDtjsC5g/DQDIGI6ODRzfCIHIGv60xcDv5oFIECj45hhaqLhgJIBIAqYYLUF1gp4ELhbwJeg0FIAxaUKEKsHIAn5U41BYBC7iIkT8gm4CHw7CEd6MEbR1xiFCHzD8j4EJKdRP5CgKA/4BiRCqEAEW5GhcCOQqH1rgGhaXI4gaHyFqExZKxxCDzUFwByBhATabz1y2H2HMA8RSG+jbor4uEOEkR+q0LLw+FuHzBj4wQLyi7fC57oH+RRFIGYETBF7oFkGNiYZT7f5s4tKraDaJDIr0ryhyAACqSAQuUauw+wYiuRq49auwAA2iAGgMUZGj5FwrQA0SUT5AAEIsARBignDnCtGNE5RiQDHtE6BpigwjFNHGCGD2HHAwA0D1F0AZDGSIoYQuiyJGCpAQAiGTHRQYwopFD3Zli7HNHjE6CnDgohwnE1I6oEgnFoRNH5qJq6qtFLErEQBKj6hbE7H1GDE+Q3GuoLFoBvENydjjHfFyBAl/FdH7IlTzEnHNr1BQntGIlsC9jQB3G/HtEigYAGDIlTGZGHT4nRQn7olQBqDEmdEQgLBgq6oAC6g8TcDhAh/0dRbRTRLRWJTRXR8ABgvRUAZwlJrMlJYxbolJ0x/I+o8JixyxoJnxxwEJQJIJiKopgoipJxqpugFxKgVxMp7xaxz+QoEA6pXJexBxgOc41xNqlJDxcaBaDALxpp/xjqlJMJ2gcJrp1JcJjp7J0UqJ7ACJ6wTAZJmJvpPkOJeJJxJ+4phJKgZJFJUZsZxpJUUABIDJJGyqMARR7RwieAdRlR+RqQyqCx0YWplxRZ0qnSd80AFZIA6ZuRhpRgWZfxuZdRRwfRKAtSCxRCHCXZ20nZYACxuaTxhamJkQOMTAdA9KvikMna0av+aIA5CxoGGY7o8OuAgGGYS5tApGl425emgwyA+5PGuQ+5Qm0E+5TI0AHphwkMZwCcHRY63ZrozAU5wSdo0Ac5dgNEBEa54iG5SQpwief0qAfZ9AyKfKz+MAiM1ZUA+5kisFhUQu8wag+5Cge+GA+5si+G+5y4x4f5AF7ZApZgEQMFiKcFYFEQEA+5zATc+594GwBFExAYrolgrOAFKg/IZFcmYFgYbFDsNZCAdAtZc29Q+5UwwZKZmJXgBgnozCbYuCh09FSZIoxglgy5SZ8ZCxV5NJMA9JY4CAj5UA5F+AbZd5pwS59ZjxSgNSDR1RJaYinFhRLZZRoiClrS2ZjxuwiEFg9KrwyyyAMAtOE6iKkSbZekvOyKxg1mCxguoKAAakcChLFRFULlFYKNKXFcigAIIwpJ4dFxjfnc6pWgrcUnjdgpWRUQAABSwJh0zFdAEFiAKE7oEayxYK0pjV2xzV0F+80AHRAVlpxVVVOgygWiCxxEcArWEArV3VUFZVsVd5JFslbVuRmVS1fQZVA1fwxxw1aVM1DAdoCAE19201/Jf0m1fVzFWVEAAA0mgHAHQP1YVQsU5a1ZkGta9dsXIFtYNSdZUNNRCQtYcCVciqKfxSsrQAWaof6UOWClUXIBGXWSDVVbUZFrtcTslc+LABNXlROgVQwEVQheRTOLtZ5HVZDQGGNXIgsYwEdQsT5A9U9VAATUVXxexaDOmdhWtBcCIMmMQJ0ErFiNptyH/NzZeGMuFtRq0cZGRl+pxqwgvqdW4GjV1ZBVjdzhtVUDud9cjbnAsLBb6ALAbeRYoZRKTGLCbdoQPhiKsNdMbZKORe4CHgkhbbKGgFgFUHjO7Z7QYAUbLYzgro5Esr7Yjg/vAh7REKDimokEcAsIYSbnHREGoWHWZIkrefHWoWbXlh1DUEnYYckRcPuLphBacCuOoaXeXYjpQg7iAJXTkOylngTryPXZshyhznPjKEqk3PgOIOmpQKmhPF0JdNak3FJvBjULRUwOZuWMyqAocXACyTOgYAvSyYjgEPTCvROIvTkN2u1HnQZMZAxOoV+kfe4YAWxIEIuKfcRH1khvvnjE2JYsVYULfboLPmGHuM2CDfsCZd7S/UUCTR4W9DIFzqfWgKbf1g/X9qsD/YA7ioedkjEO1DDDTnGMCcbI4aTizodXQJg+fToYmLwJGGg7g/g/MM7VVPUhvmTug3g9vuyopVHn4MJHIEBW1UcBcIELcOFmTDSoQJ0H+IBcBUcGMnEIkGwyI6gPLYZgEoQi+dsTdm5OOTkMfYjrLKAgo8fdneWIEIVi+J1v5PeJ1mHYvMAcY2YDo86umnXBY0oJQ3YkHWZIcGxcbuoC43GC7rJmEW1ENMukdJ4w4zNukh4zjIXbdnBJzI7UcMohNNg7MaFbE2HWMLyAkzE7IhkJnhmEODIKk9E0gLE7wbbZ0JoBhWFliAIAI0PQIyaH/OhRLbIxBhIwzpgDPXjBPVvBGlKO48fF052MA9iPTInkWB/ZasRsxPZjOhM9bdDMrKBDuV6PZlY02DIG5NM+/Yg0OAI9YXyAgB5GtThNg5EPsx1SEcAwHvAns11TAC6GkFA3btuvIyczcyEaM9KFblGOEhgPmOoTAF8z85geSLyH83AN8zWfc4PjyJ86Cz80U5yKkbQFRZ4YSkYGI5MlRW0007SkYO6BEH5D01Rbi9FGHWQtizNXiyLmhoi0YJLtS5AlbBfYmPuFzlRSLFY5cPCGS+fG84/fBnhMihAAAF4kp5IQBCszN+arLM6ivit3P3127XS8gyvCsbOfzHRQt5hQCFQCvCtGNas6sQDurSi0K8gYD6tivCu76B2hymvmvitwuNhJLgxJkcD8DabuseviDuWcqS2fTt0qCYtAyaWZBCLeW+ViKNWSgrI9ORsCX96trDYG0hA8tAuJD/nSrYPpvV1Qs1Dpv+34aXwJESIQBYDhPMEIoXG0FbyVtnjyuwQTA541tBPfJFu5A1vhPU4x41sOuFxdsuhIBTan69vAt0BqH/RRjiKCghzYMG1xOb72EQCQD5gOzzF4CgDQQERHys66X4CgAzEAD6hAhe9c/I+7FJqBB7BI/9B7TqbkB7pAx7B7wgM6B73AJuB7ggL7p7Eg77p7vAX7cgZ7R717p7C4AHZ7V7y8oHTqUHgHou/kB7Qkv7cHb7PTiHP72DiH/7aHp74wyH+7TwCHuHn7mHp76URHgHiSFH+7cE1HWI1HXADHTq87+7oEDHJHLHAQ1H4W3Hz7pHgHi83H2HLH101HUgYnGHhAAAvlJ86OuLYBEKu+u9AJuz09ux6Wu+DF6IbDtGCo2WCru+AL6JPGTigfdBQLJ97gyuIscLkOe+u4Cp1D3QEhZzuSmdaDZ3kFew51yDwqZyhqQJZ5UNZ7Z06j5/TM5xZEF+5557kA+5p4Oagc5651Z7AbF3xz525M55wNFyF3kKh5l/53jEF5mZ5aUYZ4l45M59wJZw2RsWCmV3mrsD50JEV0JEF99WsQjbmS198M56LpZ2UE2U1qjRV04c5xIJZ8TSpwNWEDEIV+ACgTl1WeRTANlcrSoM10Z//dl5Z/Sjc7OL2PmGN7Fk2H0jHOlF0LQk5ygcmGd+SJphvtd9F/mM2sUlt4l3dwxg9zXVd5QkV19+d4939ylyClABUNGwGHIPMEoJ2cd68C7GKMqsWngD5QwH5Xpoim8GEc8/Sq5aWu2F4P9D8NchNUdaNZAL4toE3KLBMDJ1DXp/V0p9t3XBcqAERYKZp5EjUGgPgGj/SoN0GYZ9z60Xz+G5Z+LVtlz/5Lz6j+L6as56ACL/UWL+jxAJZ8pMLzL6rwL09LjEr9r3sKIpZ8HFr9g7L+UZZz2RaGbzzzr+rzslt8rxb8b86Pprb6L3L2r3tw+h7yr177r868gd0wb+b/b9F/K377L/zw77nLRtL2HwH7H+eaoKH3b0n5Z5Ixw5Emn57zH5ny09O7n/7/n3S1H+H960SQn+n6XxofykYOXxn/Tz8A9VVJKBkMz4l4uHAIZxzzSOe3neZbqtg334CSP0P/F4P30akHx1PwKTSKh2sOUMGQP6JWiVezzwHZgKkKv/UVvxgMP5v/hmP0f2tKkJPwryv/5FPYf5fyf3fxf11A6bv8pLf0//f+/4/2dBYDv0Y1uG/9/wdLMc9e5/fyMHF/7YNwBG/CuAf2AG5wvAoAo5vwgtAQDQEyAn/tALLTmgf+cA63j/0f4aJUBjvN/oQLgGEDH+pmIYEQIPKfw3+lA5AB/3oE9gKBD6agdLn/6YD2B7IRgawK/5QZjSu/FcgqUwFCDjScA0QYgI9z3NqBu5bfpgNkGwD/ICgyQQLBdjUCTyb/DQXAI0EUCJMNZXfinzSCcC9BaQOAYYJUHCNs+1ArPpkCOBv8bBIFD/g4LsGP96m2/Xfm4IP6YDPBTgwvhYKorUCAhmAgIXAICF8D/WAgv/hELoF8ojgmxAwbEJngxD6+YgmNNZXtLUDhy8aZ4hv2b5OUTu3fQzrYB/QFFlSB1Zfv5GKEUYIApQ2UoinzY81sGVQ9SLUPeI1JnOUYWZK0NBLCkmhXQsoWiEqH9C6hBoLwEMJKFlDLA6A3GJ0ImEjDbE4w6od0JVLu8+hcw94lLEWEtCBh/ArYX9GWHJlI+awpYWUIcZ7CahZQ0IucIOG052Gtg5Xs0P2FlCrWUvWYScJGGDtrhOwiITL2hLdE+S5lX4e0VZjvUmy8AcUECI5LjFIR0UA0vVwlKzEDO5vP4vsTzwWkYRpxN0OcUuIYiASmAsMjUmEpwCwybpYkLvxJHUkaQ+Iv4v6WoFhlaR1I7EriQxGklyRfxUkoyIJLRDiRKI9tpO3B4YiMY7bUdtAHHavERhcIo0oqXN5lD5SxpXWjKJGGalpRedRCIhAiD19TgXXfIhcGb70o/g7fTvip1nCJ0HYO7NdjJyk5AA===

**Comment by jwyt14** [comment]
Playing on Kongregate using Chrome on a Mac

**Comment by sparticle999** [comment]
Thanks. I'll fix this right away

**Comment by sparticle999** [comment]
This is fixed now.

**Comment by jwyt14** [comment]
Same happened at 100/100.

**Comment by sparticle999** [comment]
This should be fixed. Try refreshing and trying again?
