### ISSUE TITLE
Launch Rocket, requirements numbers, red color missing

### ISSUE THREAD

**Issue by duianto** [sparticle999/SpaceCompany#90]
When the Launch Rocket objective has been unlocked, then it's requirements text:
> This requires 1 rocket and 20 rocket fuel.

shows the numbers: `1` and `20`, with black text:

![launch rocket red text missing](https://user-images.githubusercontent.com/13420573/26848194-e3cf9bfa-4aff-11e7-880c-b96fbd4ddca5.png)

The experience so far, would indicate that the numbers should be shown with red text, since the 
requirements haven't been met:
>Rocket Fuel 0/Sec 0
Rocket: Not Built

Here's the exported save text:
https://pastebin.com/s0yhxENs
after the Launch Rocket objective just had been unlocked.

**Comment by sparticle999** [comment]
Huh. I've never seen that before. Guess I missed those red costs out. I'll fix this asap. Thanks!
