### ISSUE TITLE
can't build a rocket or build fuel factorys

### ISSUE THREAD

**Issue by manacar** [sparticle999/SpaceCompany#91]
this is my save game: N4IgbgpgTgzglgewHYDkCuBbARtEAuEABgDoAWYgZhABoQAHAGwEMYMn9DaALCJgF1x5OIHv2gBlOkwDGEALIQ+TBgGEEMPvgDsAVkL7uvAVADiEDGo34AbAA59w0cfFwGcackua8OgJwPDMSgAFQQAczCGCAATfD4oNAhaRhY2PncOZOZWfndJGXlFZS98WwBGB2EUnPTpFzcPJBK8LQAmSqzU3OkFAQQoOAFm3y0q7LT3UIio2Lx4xNoIJGgwgE9S0gpyVtJ7Sv1bWix+Y3WhI5PoVd7i9W89AJBjvlOzCzv8B4Mny6hV/NkN1UHzwFA6PxeV2CrUyENO0KBzR0X2Ez3hrTeSJRF0hf2hAMKSmBVlBYMe0i4TCgHmUAFEkGE4Mt8O1aBSqTSGPTGctESCKBRrGzKdSEHSGUyIJiQWU7MKOWKuRLlgB5NB8Ojq/CkWgwBDMKAABSYywY+DBuv1VONpr5JJ0rQoloNNogDGlJOsFWd1pNbrVGq1eDKxB0tAwikpy3ESnSyFhEb4UYgMdyyAJdu8ZW9IETydTcaQwUGJrgmGGwiQaGkUSpBcQSFhVZrvCg9fTUkBRWJ3naj2btbbsYbxaUSDL7xJFUebDCE2kCaYc+6Ge7zVaX3DS/nHt74Nn8/qkCgzTKm5AADM0PBkAAlXjSPj9WFXm9Ie8yJ9tzuE24ksnfK+DYfo+/SjqW5Ygn2gHXsBD5fvU7ieDK54IK4LI6NY3xoQwMb9EuEAYVhwg4SgEAAB58HhUAEZ8ZR9skmB0PgOaahgdCZixyKMexu50TxdAAFYyAA1ixVRMcJ0giZxeDWLsAlSSJfF4K0rL0JJokqq4p6tL4ilaeqmpZiRrgAGJwG6symQwFlWauRLrqQ2HmZZDDROB46QSSrSjDZdnuYhjTNBQ/g2becBhLCOERWEDl/lmvjOeFkWeROp52C5DCxb0ED9IMEDNFoWHht2LGtHspVEtRtHBhV3yJsoZGUTVYSEapmENZKUDasIGDdbJpAOuG3UAOoIAg0Trq0QoiLwYCrAAIgMDBmqpjjzUtK0MLJFTFYEC3La47rmM0zlOnNTCHdt2k9uagoHVtx0BsZLGzYyYRMEdq2wh9X3bfFd2qZVIB/d9J2Tt4WzfGDAOuEhTQgqQ060AAjmgJp8Jg4OwujmPYwDP6yXpjx40gWMYODJj6lNMq2H5aMY+TBPHbl+VDCCYW0G1GA2M5Wiho6vjCyLwtaNz5ite19EgzzzVUV+tUbsREsYHI3XmsIPPq8sUDE16qs69AKllFoOogEw0RgCasjRDjqm0Jb1tILb4O7UNjtWzbMRU6dUGkK0nvO67N06SCbRB97ds3UZQaHCA0RwEwGDINHx2wonyep+DgMhcltCZynSBp6tKl7MIhfZ3DDTISSQ3fNIVJYKsyz28IjdQM3reEwUxPTu3TctxAvuQyyfkD53Q9u4oeUDBzJIg+yorKHzDcipyUur+36+KvLm91YvO/KFMkQxHECRJCAADuE3RFgaBQLrnzCDfk334/0C7abF2v3fD+6+NSaSJbCzSvI/AoL5/69zXCCewtAwFIAKIA2mddhAIIKLdU8MFwGyGQQASSQK9Oq8CoGyBenHWgIlXCNnOCAKhDAkC535A8Sh1CVLWAYnQ6hQVa5QxBheP4gg0GCO/NAxyKF+EiIADJXSYLpFhl4RFsznoVEEnVaC/y3ho2++95LfF/nvRWbVyog1/tIdUxhn7aMmuY3EX8tA/1vrY4wyDgGzWyNAFQFjBA5g8SebxesYFTj0rQPxXjcQqUdBdMJATMEykINElgnjYmxyzIHBOEALz9AgBoIRBdMnZNyaIrs4j/yPGiAUqAOTjBpW8r2BmGSslVKKTwxGPkFFMlfHkkAnTrwSCJkErMxFhC9JgNAOJ/56LfFGZ/Ge7NVF138LqaQlkXbtUFGeMgpthkOA3OLEAzAsC9VCUwLArikbDQOac9hWh46HNkv4MMVysDQk+Ccl5rRzkL0IE8w50IVIUDUu8hEgy3q+NOcEKgtC/kUC+d4XwKtnmQpUqQBpMLdrj1oFABA0lFCwmxbivgZlEhrWEASkSihiVuhPjMc+CwQAUnMO4ZQhpmDk1hIy/qjcGCssxrtckPAuUsrZXwFSuht5Mu5by8mEz7jYXInAROMA0w0JIgqpVKrdrQVoAgdVcBlWFjLmSHVeqDUNllTYEGMABlElhNasRyh956F1DapqFEFb4WMcGBqkY/QJl9dGIx7VnW5gDRAQxnrpbfHSGOCcsIY0QQwE64QCavIYAjTRL1KNQY01+jTZN3MaYZtqtm+ADBjx2tcMeAtIAy3HmLVm74ZaEaVprowoNVja3w0aA2qNfUJpIHGlAClPVaEp2QEOkdKkFHjqQG3cMA7p6lJMg1Rd212GruQODC1eB865gHQARQxlAP4CZD3Hr+Ew75m6kBHqpH8adM5z33v+N23h5oFEpGWHwWk5FG7Wy/LCL9ihf3/v4GBEsaazrnmAz+v9sivx4NkCFTF9A2UgfgwB/oyiCpIm+NbcxmBYQEbQJgK9craAkcwI+4QMBqyFlAwh58tC6OPgbIxrDxTfxA1LfR9jmHwOmD9te3UfHkAccEzuxF9rkMICvnan8agr7kfEo8GTqir61NHngMKtHFNydaWdbNkB2W0JM1RV1QMHSPHMwACTdOlJGqHzM4fnlDJZIAKKMGyaO4QXmGA+ZNmpyz87a0hZ7iUhKLIm3heOmXGLDqGDbrDlOR4dAlhKFC+l8m/1joqeDMlKoGXcul2E1mfuyRis5zfW0+4iLU2hYaxF7jzRrAAVoE1uLNN1yoc66tVzCzvCIuiNixVGdRvRHy5wkbaFoi9GTHh/JGhsWrG6RU5bCBVtcdkgo9b8RNvGzK1xb4e2VvjJSyuiuRguCpl8/k/gN2lDbdBcGVDFSHu3aPJ4mUZ4TvXc+zV5othOGfgxoB2hoPBP5a9I8SHX57NuDqVxBpcPsNzJUa1ptHggy0exxZxLWDccIHVFp9cemCgyLGXdsLFOknPeXR+8nshKeHe01zGnzO6c7qmaiaASZ2C0JwFAfn+Wyi+AUUL/npO6acMl5SQzP3yQmiQPGWhjckAq8YZZoHOhs3q81zu3wFBF7K+QANpE6ksABavl+CksIrdydtzd7XKFUTW6d9Lspyz+iMupzADw1IeD06iz4LHPug8m04f78P52eOIuV3ALgrhBOwgT0n5gCEXdlO+Gn5PX4jU5414nvP/Qvsnn9n9qn3grtV6m+CdbfOFdTi0A0hvwvzdI2+M01sFIACqSAAu4tmPMS+3eOQ8FmAAbRAGgAfOKRKb1oLPwfIkABCLB3D0hWOsJfc/pK3RoDPvfC+rQ9V3yvuQMgk/LBgIf5f8/FrVISGx+MS+6BhBohU+8eoH6yGCBAO3c/efcQU/cQVYXJXmIA6SGRD5O/d/T/CAbkSUf/QAo/FfW8efSlElV5AAXUdmtmTyt3amn3v2kkXzQPn3X3gGkC3ygDWDv2PwPygJPwNAYIvyv0lFvzfw/0tkQOVAgBQK4DgJ4IqRAINEELYOANAPAIEEgJn3gN4O/2J2pAEIAKEOYMf2WzE0bGYJgNeWYIwMJSpQYH0IoOgIhSoDwJACUCwBgH7xXzPjwGnzH0D2CFOUPz1ANDAIgLcKOSsOaWUNkDsOP0cOnyWG3xQCukPyXk5EiLAEP1IiiKxUwKJWwJhCsJV1X36AqVHUn38JSJkVn0ZVmAvGUDGQ6zUPsMwJKLKMvkTFngKiqKH3wFKIYHKKeAsWQBgFs0VQqRoTyMWHIm8yqSnysIfkTVhHGLTRrSmInF7VU0djYwA1CKsI/yZByN+gGGLmgE9z3Bhi2JyPy0K25gOONm6ygnJDQCwAyDVyuPcF7xoig1gXbjuLqCz0uxeOuOkG53BCWAGF91hD+PcCDym1Nm+CBN912JZHa08yQH+JBMBxlAoAUSqWkFWBbGp1RPRKiGDyBiN2zSxIxPmz9DOlQ0JJxI7wXgtCuWtlhGYGthrXpKYHmO9XbmfzgCII5XZKIKOPJG5KiHi3BMoholAmp3dRFMzwJxlGGUGPiE/Ag1jSRzqkeHFPlLbERM9BVOFLQA2NoXFJ1P6SlM9F01lISByKhJ8FQ31MOI1PcxszdDQDoCxhTzMwdKdLB1L3eJZF8HLkozdOdPz3OOCQq3AH9I9MCT6Ax3DhDS4FWBmzalVW4DjOxQTJrVjPjKWBZL131CiFFI5RzIAMlMiyBhlIZQLNFItN2AaiXG/UXDCG/VF0IBBlnG/QtIRWrPrMUGpncla0RUKjdFJUWBUAHLLxQ04X7NLiDKhgDnBOHNWib17B0BBmvz6PfiiloRXKWDXNFzaEeE3KQDXOJOWFPGhm+H3MPPR1w3DhzB4ER15g3IczIw7VD0MDvKzJO2xWZFoRm2jC9LwFsD3R/JTFtJsEeDHBHXjRNBHVFxmmjSgp2Mg0c1S04XAokBAv/L3Q8HYmaT1GpywroBws9KNKGxhPwsIpCEQqVM2EXgQGwpyVwoXI/T3RgCoQwAjD91YvYqm2RDU04oQsVO02/l4rgDYtmUjKvJJBbxGVkFhHcBTGfJDTkvfOkogENHcDEloTkrUrIL/NNhBi0vUpNiN2mVkFCzkpzj/KFhMuHm2gtNaB51oHMurgRlPHbOEQgAgAAC9ukBEPLvLcTTwwTAIqkvL+LE0gdSzfLQr1S20ioYSMAoAzIQrvKExErkqIA4VzQtATTcw0q/KIAEckKsxjjcqkr8rKSswZ1LyBB/VxKBAa16j5llKqoGiBAaVHCR9kgtjLFaECKmRnBdL9gur+q0LYq1FwQr4IAjlaFJqsB8tjLHhZqHjwqkZdMX4prGKfB+4K5wDVcdq9QixKLtMAITtdqkBuyUEPj9r0x0LoJTqDqKrVNrqkAkNBsnqYsg92paMr4qR7yyUmR1zhAOCIBIAIxyZb88BQBjw3xtRFhyYBgcl8BQAr8AB9QgFiRYrgFGsoDGi2CkFGmEYMTGlGqFMoYm0gVPfGnQXG1GsoWwSmrGsXBmgm6wGm/GsEZmigHGiHdmimnmrG5Ezm+m/mlGgONmrGzYZmkBDgAAXxlt1GHA0HcAhqhugBhqJthPiEshVtzBNAxmyhyUCMRshvAHKjJvAAF3ojKHlusMsigBVCvmWGiG5qhpYjgQtrdsIBtvSHGUdpiEJtdstMowFx0C0G9tOWCIcNmEDqeVpJ8BtoCN/xySaIpWjtNrkmDpsG9rUO/x7wnyRvTv0g9p0xtrGRgDfGLAjALviNUh2BDFRVFlFnKHNjjrUmRjIGysbuFmbu9pEtUuYFWzTprrbvrs7q7ubsztrvbobq7p9LKFIBtqaTSB6trS4H6D4EiKrqOBpnpFOVpTwFaPaPgAqWOHLzovLscMPsviTHMHah+DGUPyYHVAQHECuggAIWMGtjWhOrlqxUNqTp1prqeVHVAHCLoLOFAETJnxaNqJtuqDYALqgbQBgbaIgBttmKIxNqQZQbGRtqZMQcmJwbQZ1XQiwcIYPtgaqhXjIdoWQbmAvhtp5gIdobpWIYZSPjWkgfIavpts0RoeEDoZH1Lpq2YYEaIdLss1EaX3EaqmTCkegYodQd7oEvkboZ4cLXclUZka7XLUEC4ZYcUdwaTIzJoX0bEcMbYdvLjX4ekYsZtrkq0bsZavmUcfUdrRWSWBkpsYUZ4d/o6NcETgZEAdxrgALrAbWGCG5r811gicJuie30hUBJidWGCD5vifAeCGpr1OSeCFZt6vGCYEiaAwKdeVoceInCKbKcTVKYEfKcwESaqbTVSbpNkUqeECZJqZOWtgafadabSZIZMKiYGc6ZABwh6eGf6dDSJDaaoZMLidmfGamePkmZ5hmdBnMBGdWahS1g2cmZiMVDWf2ePnmfYYVGPm2flGXhMMmd/jWduZOduYuevlvmaZYxqzWebUaBGc+eQEWZ+aLEmfUyBA+cs2+dBaeaBe7Feb6jDTWbzD9BGfheWEWaRYEMmdTQqaGdtoEpGYxfqaebxYwGhY0Y8ixbCBpk2YpaefJfcmJZ0ePA+arR2JObrR2IhaZZCEmfTJTKWDWe5fCF5ZOf5YTMWeFd5a5cfKJaxasfqaFcldFflcmbkrWeVZOeVaeeVcmcapUTheqoEJZY8bWQ+cNb/wNdWT/yefJSwOpSxatdSOpTib8YEDtxNprvNtCZNo0EjV7wUIqV5RyDtSDR9ZEIgGWrTUDe9d9YgBkTjtoyDajYPxY3jZDaBAjczVDajbeDTYImDYQJUA4ezbalzd4OQULYzZDdaTLeLdEMkaTcjZTbDSraja0ybZDYutbYQLLw7d4Ns2TIFaga9fTerYKsle7YqVerHcJFaq+uYKoM32ScmMYNcENAJXooBsXZXzEKpA3fnyUKTsvwpE4J3ekk0PmBfyQePy3bbBkPMGPZEj0JOdIPvaYDoEWaffX1xBSaxffd+BScfeP39bYDWafcA8Kf/ZX1pAwAXFoePwG2A9g71ZGafbg6eafcWjOvEB+qgD+o0Iw7oE+smKjb3ZUIkNoajaQORbUMI4rdP1I78wvAvHcHNdWFzvH1ltLsUHSCCerrVobFxoywRpVrlplqAA
when i press the botton to make the fuel factorys or the rocket it does nothing even thouth i have the stuff to make it

**Comment by sparticle999** [comment]
seems to work perfectly fine on my game: 
[ice_video_20170604-202423.zip](https://github.com/sparticle999/SpaceCompany/files/1059309/ice_video_20170604-202423.zip)

**Comment by sparticle999** [comment]
also, I can only message you on Kong if you are my friend, or if your account is public

**Comment by sparticle999** [comment]
Maybe try playing the game here? https://sparticle999.github.io/SpaceCompany/ It's a more updated version of the game, but is a bit experimental

**Comment by lejonmanen** [comment]
Maybe related to #87

**Comment by User670** [comment]
Uncaught ReferenceError: getRocket is not defined (index):3464
Uncaught ReferenceError: getChemicalPlant is not defined (index):3406
Uncaught ReferenceError: launchRocket is not defined
