### ISSUE TITLE
[Suggestion ] See balance for each ressource

### ISSUE THREAD

**Issue by Thomas-Bo** [sparticle999/SpaceCompany#92]
For each ressource, it would be more easy if we can see how much we gain ressource/second and how much we depense.
For exemple with Wood, it could be like that :
Base producton : 50
Charcoil consuption : -45
Total production : 5

I hope my english isn't to bad and you can understand. If you can't, or want more explanation, i'm on Kongregate : http://www.kongregate.com/accounts/frapsy

**Comment by sparticle999** [comment]
This is a feature of the machines tab. Check the subreddit wiki for more details and a sneak preview. http://www.reddit.com/r/spacecompany/wiki
