### ISSUE TITLE
machines costs

### ISSUE THREAD

**Issue by lagauffre91** [sparticle999/SpaceCompany#94]
The cost of a machine doesn't decrease after the destruction of one.

Maybe if it's possible you can correlate the cost of a machine to the number of machines owned.

**Comment by sparticle999** [comment]
This is the case, but there is a bug where the cost update only occurs when a new machine is bought. This will be fixed in the next update, which will come out soon

**Comment by Craiel** [comment]
this was fixed / added in 0.4.4.2
