### ISSUE TITLE
Plasma

### ISSUE THREAD

**Issue by Modrov** [sparticle999/SpaceCompany#95]
Hello,
First of all your game is awesome.
I bought the plasma research at the sol center.
But it doesn't appear in the ressource tab.
![capture d ecran 2017-06-08 a 15 27 08](https://user-images.githubusercontent.com/29279817/26930855-f673a0f2-4c5e-11e7-84ff-a689cf516779.png)

**Comment by sparticle999** [comment]
It unlocks the research, not the actual resource. Find it in the researches tab. 

Sparticle999

**Comment by Modrov** [comment]
Thank you very much =)
