### ISSUE TITLE
Number of rockets nor displayed/used

### ISSUE THREAD

**Issue by Coeur** [sparticle999/SpaceCompany#97]
I think I was able to buy multiple rockets before exploring the Moon, but I've never been able to see the count of rockets I bought. And I never could (or had to) buy more rockets after my first exploration.

**Comment by sparticle999** [comment]
You can only build one rocket total. You only need one

Sparticle999

**Comment by Coeur** [comment]
@sparticle999  But I was able to spend the resources for building multiple... you shouldn't allow clicking multiple times on the button.
